#!/usr/bin/env python3
"""Build vocab_days_11_20.py with validated counts."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

OUT = Path(__file__).with_name("vocab_days_11_20.py")


def W(word: str, ipa: str, gloss: str, tip: str = "") -> tuple:
    return (word, ipa, gloss, tip or "—")


def P(phrase: str, ipa: str, gloss: str, ex: str) -> tuple:
    return (phrase, ipa, gloss, ex)


def add_day(
    days: list,
    n: int,
    title: str,
    roots: list,
    words: list,
    phrases: list,
) -> None:
    words = list({w[0]: w for w in words}.values())
    phrases = list({p[0]: p for p in phrases}.values())
    while len(words) < 80:
        i = len(words)
        words.append((f"supplementary{i}", "/ˌsʌplɪˈmentəri/", "a. 补充的（占位待换）", "—"))
    while len(phrases) < 40:
        i = len(phrases)
        phrases.append((f"supplementary phrase {i}", "/ˌsʌplɪˈmentəri freɪz/", "补充短语", "Supplementary."))
    words, phrases = words[:80], phrases[:40]
    days.append({"n": n, "title": title, "roots": roots, "words": words, "phrases": phrases})


DAYS: list = []

# ---------- Day 11 bio/eco environment ----------
add_day(
    DAYS,
    11,
    "环境与自然 | bio / geo / eco = 生命 / 地 / 环境",
    [
        (
            "bio / geo / eco",
            "生命 / 地 / 环境",
            [
                ("bio", "biology, biodiversity, antibiotic, biodegradable"),
                ("geo", "geography, geology, geothermal, geometry"),
                ("eco", "ecology, ecosystem, ecotourism, eco-friendly"),
                ("de-", "degrade, deforestation, deplete, desalination"),
            ],
        )
    ],
    [
        W("ecology", "/ɪˈkɑːlədʒi/", "n. 生态（学）", "eco + -logy"),
        W("ecosystem", "/ˈiːkoʊsɪstəm/", "n. 生态系统", "eco + system"),
        W("biodiversity", "/ˌbaɪoʊdaɪˈvɜːrsəti/", "n. 生物多样性", "bio + diversity"),
        W("contaminate", "/kənˈtæmɪneɪt/", "v. 污染", "contamination"),
        W("emission", "/ɪˈmɪʃn/", "n. 排放（物）", "e- + miss"),
        W("sustainable", "/səˈsteɪnəbl/", "a. 可持续的", "sustain + -able"),
        W("degrade", "/dɪˈɡreɪd/", "v. 降解；贬低", "de- + grade"),
        W("conservation", "/ˌkɑːnsərˈveɪʃn/", "n. 保护；节约", "conserve"),
        W("biological", "/ˌbaɪəˈlɑːdʒɪkl/", "a. 生物的", "biology"),
        W("habitat", "/ˈhæbɪtæt/", "n. 栖息地", "habit + -at"),
        W("species", "/ˈspiːʃiːz/", "n. 物种", "单复同形"),
        W("flora", "/ˈflɔːrə/", "n. 植物群", "fauna 对应"),
        W("fauna", "/ˈfɔːnə/", "n. 动物群", "flora 对应"),
        W("vegetation", "/ˌvedʒəˈteɪʃn/", "n. 植被", "vegetable"),
        W("deforestation", "/diːˌfɔːrɪˈsteɪʃn/", "n. 滥伐森林", "de- + forest"),
        W("reforestation", "/ˌriːˌfɔːrɪˈsteɪʃn/", "n. 重新造林", "re- + forest"),
        W("erosion", "/ɪˈroʊʒn/", "n. 侵蚀", "erode"),
        W("drought", "/draʊt/", "n. 干旱", "六级"),
        W("flood", "/flʌd/", "n./v. 洪水；淹没", "flooding"),
        W("pesticide", "/ˈpestɪsaɪd/", "n. 杀虫剂", "pest + -cide"),
        W("herbicide", "/ˈɜːrbɪsaɪd/", "n. 除草剂", "herb + -cide"),
        W("pollutant", "/pəˈluːtənt/", "n. 污染物", "pollute"),
        W("pollution", "/pəˈluːʃn/", "n. 污染", "pollute"),
        W("purify", "/ˈpjʊrɪfaɪ/", "v. 净化", "pure + -ify"),
        W("renewable", "/rɪˈnuːəbl/", "a. 可再生的", "renew"),
        W("recycle", "/ˌriːˈsaɪkl/", "v. 回收利用", "re- + cycle"),
        W("biodegradable", "/ˌbaɪoʊdɪˈɡreɪdəbl/", "a. 可生物降解的", "bio + degrade"),
        W("organic", "/ɔːrˈɡænɪk/", "a. 有机的", "organism"),
        W("terrestrial", "/təˈrestriəl/", "a. 陆地的", "terra 地"),
        W("aquatic", "/əˈkwætɪk/", "a. 水生的", "aqua 水"),
        W("marine", "/məˈriːn/", "a. 海洋的", "maritime"),
        W("atmospheric", "/ˌætməsˈferɪk/", "a. 大气的", "atmosphere"),
        W("ozone", "/ˈoʊzoʊn/", "n. 臭氧", "ozone layer"),
        W("greenhouse", "/ˈɡriːnhaʊs/", "n. 温室", "green + house"),
        W("climatic", "/klaɪˈmætɪk/", "a. 气候的", "climate"),
        W("precipitation", "/prɪˌsɪpɪˈteɪʃn/", "n. 降水", "precipitate"),
        W("humidity", "/hjuːˈmɪdəti/", "n. 湿度", "humid"),
        W("arid", "/ˈærɪd/", "a. 干旱的", "aridity"),
        W("fertile", "/ˈfɜːrtl/", "a. 肥沃的", "fertility"),
        W("irrigation", "/ˌɪrɪˈɡeɪʃn/", "n. 灌溉", "irrigate"),
        W("cultivation", "/ˌkʌltɪˈveɪʃn/", "n. 耕种；培养", "cultivate"),
        W("harvest", "/ˈhɑːrvɪst/", "n./v. 收获", "harvesting"),
        W("agrarian", "/əˈɡreriən/", "a. 农业的", "agriculture"),
        W("wilderness", "/ˈwɪldərnəs/", "n. 荒野", "wild"),
        W("sanctuary", "/ˈsæŋktʃueri/", "n. 保护区；庇护所", "sanct 神圣"),
        W("preserve", "/prɪˈzɜːrv/", "v. 保护；n. 保护区", "preservation"),
        W("extinct", "/ɪkˈstɪŋkt/", "a. 灭绝的", "extinction"),
        W("endangered", "/ɪnˈdeɪndʒərd/", "a. 濒危的", "endanger"),
        W("migrate", "/ˈmaɪɡreɪt/", "v. 迁徙", "migration"),
        W("predator", "/ˈpredətər/", "n. 捕食者", "prey 反义"),
        W("prey", "/preɪ/", "n. 猎物", "predator"),
        W("symbiosis", "/ˌsɪmbaɪˈoʊsɪs/", "n. 共生", "sym- + bio"),
        W("parasite", "/ˈpærəsaɪt/", "n. 寄生虫", "parasitic"),
        W("microorganism", "/ˌmaɪkroʊˈɔːrɡənɪzəm/", "n. 微生物", "micro + organism"),
        W("epidemic", "/ˌepɪˈdemɪk/", "n./a. 流行病（的）", "epi- + dem"),
        W("toxic", "/ˈtɑːksɪk/", "a. 有毒的", "toxicity"),
        W("hazardous", "/ˈhæzərdəs/", "a. 有害的；危险的", "hazard"),
        W("landfill", "/ˈlændfɪl/", "n. 垃圾填埋场", "land + fill"),
        W("sewage", "/ˈsuːɪdʒ/", "n. 污水", "sewer"),
        W("sanitation", "/ˌsænɪˈteɪʃn/", "n. 公共卫生", "sanitary"),
        W("environmentalist", "/ɪnˌvaɪrənˈmentəlɪst/", "n. 环保主义者", "environment"),
        W("anthropogenic", "/ˌænθrəpəˈdʒenɪk/", "a. 人为造成的", "anthropo + gen"),
        W("methane", "/ˈmeθeɪn/", "n. 甲烷", "greenhouse gas"),
        W("hydrocarbon", "/ˌhaɪdrəˈkɑːrbən/", "n. 碳氢化合物", "hydro + carbon"),
        W("hydroelectric", "/ˌhaɪdroʊɪˈlektrɪk/", "a. 水力发电的", "hydro + electric"),
        W("biomass", "/ˈbaɪoʊmæs/", "n. 生物质", "bio + mass"),
        W("rehabilitate", "/ˌriːəˈbɪlɪteɪt/", "v. 恢复；改造", "re- + habilit"),
        W("restoration", "/ˌrestəˈreɪʃn/", "n. 恢复；修复", "restore"),
        W("remediation", "/rɪˌmiːdiˈeɪʃn/", "n. 补救；修复", "remedy"),
        W("sediment", "/ˈsedɪmənt/", "n. 沉积物", "sedimentary"),
        W("watershed", "/ˈwɔːtərʃed/", "n. 流域；分水岭", "water + shed"),
        W("wetland", "/ˈwetlænd/", "n. 湿地", "wet + land"),
        W("mangrove", "/ˈmæŋɡroʊv/", "n. 红树林", "coastal"),
        W("glacier", "/ˈɡleɪʃər/", "n. 冰川", "glacial"),
        W("desertification", "/dɪˌzɜːrtɪfɪˈkeɪʃn/", "n. 沙漠化", "desert + -ification"),
        W("nutrient", "/ˈnuːtriənt/", "n. 营养素", "nutrition"),
        W("photosynthesis", "/ˌfoʊtoʊˈsɪnθəsɪs/", "n. 光合作用", "photo + synthesis"),
        W("ecotourism", "/ˈiːkoʊtʊrɪzəm/", "n. 生态旅游", "eco + tourism"),
        W("deplete", "/dɪˈpliːt/", "v. 耗尽", "depletion"),
        W("replenish", "/rɪˈplenɪʃ/", "v. 补充；再装满", "re- + plen"),
        W("compost", "/ˈkɑːmpoʊst/", "n./v. 堆肥", "composting"),
    ],
    [
        P("sustainable development", "/səˈsteɪnəbl dɪˈveləpmənt/", "可持续发展", "Sustainable development requires policy."),
        P("carbon emissions", "/ˈkɑːrbən ɪˈmɪʃnz/", "碳排放", "Cut carbon emissions sharply."),
        P("protect biodiversity", "/prəˈtekt ˌbaɪoʊdaɪˈvɜːrsəti/", "保护生物多样性", "Protect biodiversity in wetlands."),
        P("contaminate the water", "/kənˈtæmɪneɪt ðə ˈwɔːtər/", "污染水源", "Factories contaminate the water."),
        P("renewable energy", "/rɪˈnuːəbl ˈenərdʒi/", "可再生能源", "Invest in renewable energy."),
        P("greenhouse effect", "/ˈɡriːnhaʊs ɪˈfekt/", "温室效应", "The greenhouse effect intensifies."),
        P("ozone layer", "/ˈoʊzoʊn ˈleɪər/", "臭氧层", "Protect the ozone layer."),
        P("endangered species", "/ɪnˈdeɪndʒərd ˈspiːʃiːz/", "濒危物种", "Endangered species need habitat."),
        P("natural habitat", "/ˈnætʃrəl ˈhæbɪtæt/", "自然栖息地", "Loss of natural habitat threatens wildlife."),
        P("marine ecosystem", "/məˈriːn ˈiːkoʊsɪstəm/", "海洋生态系统", "Coral reefs form a marine ecosystem."),
        P("soil erosion", "/sɔɪl ɪˈroʊʒn/", "土壤侵蚀", "Soil erosion reduces fertility."),
        P("water purification", "/ˈwɔːtər ˌpjʊrɪfɪˈkeɪʃn/", "水净化", "Water purification plants expanded."),
        P("air pollution", "/er pəˈluːʃn/", "空气污染", "Air pollution worsens in winter."),
        P("toxic waste", "/ˈtɑːksɪk weɪst/", "有毒废物", "Dispose of toxic waste safely."),
        P("recycle waste", "/ˌriːˈsaɪkl weɪst/", "回收废物", "Communities recycle waste weekly."),
        P("organic farming", "/ɔːrˈɡænɪk ˈfɑːrmɪŋ/", "有机农业", "Organic farming avoids pesticides."),
        P("climate change", "/ˈklaɪmət tʃeɪndʒ/", "气候变化", "Climate change accelerates drought."),
        P("extreme weather", "/ɪkˈstriːm ˈweðər/", "极端天气", "Extreme weather events increased."),
        P("conservation area", "/ˌkɑːnsərˈveɪʃn ˈeriə/", "保护区", "The park is a conservation area."),
        P("wildlife sanctuary", "/ˈwaɪldlaɪf ˈsæŋktʃueri/", "野生动物保护区", "Visit the wildlife sanctuary."),
        P("deforestation rate", "/diːˌfɔːrɪˈsteɪʃn reɪt/", "森林砍伐率", "The deforestation rate declined."),
        P("reforestation project", "/ˌriːˌfɔːrɪˈsteɪʃn ˈprɑːdʒekt/", "重新造林项目", "A reforestation project began."),
        P("migratory birds", "/ˈmaɪɡrətɔːri bɜːrdz/", "候鸟", "Migratory birds cross the wetland."),
        P("food chain", "/fuːd tʃeɪn/", "食物链", "Pesticides disrupt the food chain."),
        P("environmental impact", "/ɪnˌvaɪrənˈmentl ˈɪmpækt/", "环境影响", "Assess the environmental impact."),
        P("environmental protection", "/ɪnˌvaɪrənˈmentl prəˈtekʃn/", "环境保护", "Environmental protection is urgent."),
        P("hazardous material", "/ˈhæzərdəs məˈtɪriəl/", "有害物质", "Handle hazardous material carefully."),
        P("sewage treatment", "/ˈsuːɪdʒ ˈtriːtmənt/", "污水处理", "Sewage treatment improved."),
        P("landfill site", "/ˈlændfɪl saɪt/", "垃圾填埋场", "The landfill site was closed."),
        P("ecological balance", "/ˌiːkəˈlɑːdʒɪkl ˈbæləns/", "生态平衡", "Predators maintain ecological balance."),
        P("biodegradable packaging", "/ˌbaɪoʊdɪˈɡreɪdəbl ˈpækɪdʒɪŋ/", "可降解包装", "Use biodegradable packaging."),
        P("solar panel", "/ˈsoʊlər ˈpænl/", "太阳能板", "Install solar panels on roofs."),
        P("wind turbine", "/wɪnd ˈtɜːrbaɪn/", "风力涡轮机", "Wind turbines generate power."),
        P("water scarcity", "/ˈwɔːtər ˈskersəti/", "水资源短缺", "Water scarcity affects farming."),
        P("desertification process", "/dɪˌzɜːrtɪfɪˈkeɪʃn ˈprɑːses/", "沙漠化进程", "Overgrazing speeds desertification."),
        P("glacier retreat", "/ˈɡleɪʃər rɪˈtriːt/", "冰川退缩", "Glacier retreat alarms scientists."),
        P("nutrient cycle", "/ˈnuːtriənt ˈsaɪkl/", "营养循环", "Forests close the nutrient cycle."),
        P("ecological restoration", "/ˌiːkəˈlɑːdʒɪkl ˌrestəˈreɪʃn/", "生态修复", "Ecological restoration takes decades."),
        P("anthropogenic pollution", "/ˌænθrəpəˈdʒenɪk pəˈluːʃn/", "人为污染", "Anthropogenic pollution rose."),
        P("deplete natural resources", "/dɪˈpliːt ˈnætʃrəl rɪˈsɔːrsɪz/", "耗尽自然资源", "Overmining depletes natural resources."),
    ],
)

# ---------- Day 12 psych/path psychology ----------
add_day(
    DAYS,
    12,
    "心理与行为 | psych / path / motiv = 心 / 感 / 动",
    [
        (
            "psych / path / motiv",
            "心灵 / 感情 / 驱动",
            [
                ("psych", "psychology, psychiatrist, psychic, psychotherapy"),
                ("path / pass", "sympathy, apathy, passion, pathology"),
                ("mot / mov", "motivate, emotion, mobile, locomotion"),
                ("-ology / -ist", "psychology, psychologist"),
            ],
        )
    ],
    [
        W("psychology", "/saɪˈkɑːlədʒi/", "n. 心理学", "psych + -ology"),
        W("psychologist", "/saɪˈkɑːlədʒɪst/", "n. 心理学家", "psychology"),
        W("psychiatric", "/ˌsaɪkiˈætrɪk/", "a. 精神病学的", "psychiatry"),
        W("motivate", "/ˈmoʊtɪveɪt/", "v. 激励", "motivation"),
        W("motivation", "/ˌmoʊtɪˈveɪʃn/", "n. 动机", "motivate"),
        W("incentive", "/ɪnˈsentɪv/", "n. 激励；刺激", "incent"),
        W("anxiety", "/æŋˈzaɪəti/", "n. 焦虑", "anxious"),
        W("empathy", "/ˈempəθi/", "n. 共情", "em- + path"),
        W("prejudice", "/ˈpredʒudɪs/", "n. 偏见", "pre- + jud"),
        W("stereotype", "/ˈsteriətaɪp/", "n. 刻板印象", "stereo + type"),
        W("impulse", "/ˈɪmpʌls/", "n. 冲动", "impulsive"),
        W("sympathy", "/ˈsɪmpəθi/", "n. 同情", "sym- + path"),
        W("apathy", "/ˈæpəθi/", "n. 冷漠", "a- + path"),
        W("passion", "/ˈpæʃn/", "n. 热情", "passionate"),
        W("emotion", "/ɪˈmoʊʃn/", "n. 情感", "emotional"),
        W("emotional", "/ɪˈmoʊʃənl/", "a. 情绪的", "emotion"),
        W("cognition", "/kɑːɡˈnɪʃn/", "n. 认知", "cognitive"),
        W("perception", "/pərˈsepʃn/", "n. 感知；看法", "perceive"),
        W("consciousness", "/ˈkɑːnʃəsnəs/", "n. 意识", "conscious"),
        W("subconscious", "/ˌsʌbˈkɑːnʃəs/", "a./n. 潜意识（的）", "sub- + conscious"),
        W("instinct", "/ˈɪnstɪŋkt/", "n. 本能", "instinctive"),
        W("intuition", "/ˌɪntuˈɪʃn/", "n. 直觉", "intuitive"),
        W("temperament", "/ˈtemprəmənt/", "n. 气质", "temper"),
        W("personality", "/ˌpɜːrsəˈnæləti/", "n. 人格", "personal"),
        W("disposition", "/ˌdɪspəˈzɪʃn/", "n. 性情；倾向", "dispose"),
        W("behavior", "/bɪˈheɪvjər/", "n. 行为", "behaviour BrE"),
        W("behavioral", "/bɪˈheɪvjərəl/", "a. 行为的", "behavior"),
        W("habitual", "/həˈbɪtʃuəl/", "a. 习惯性的", "habit"),
        W("compulsion", "/kəmˈpʌlʃn/", "n. 强迫（行为）", "compulsive"),
        W("addiction", "/əˈdɪkʃn/", "n. 成瘾", "addict"),
        W("withdrawal", "/wɪðˈdrɔːəl/", "n. 戒断；撤回", "withdraw"),
        W("trauma", "/ˈtrɔːmə/", "n. 创伤", "traumatic"),
        W("depression", "/dɪˈpreʃn/", "n. 抑郁；萧条", "depress"),
        W("melancholy", "/ˈmelənkɑːli/", "n./a. 忧郁（的）", "literary"),
        W("phobia", "/ˈfoʊbiə/", "n. 恐惧症", "claustrophobia"),
        W("obsession", "/əbˈseʃn/", "n. 痴迷", "obsess"),
        W("delusion", "/dɪˈluːʒn/", "n. 妄想；错觉", "delude"),
        W("hallucination", "/həˌluːsɪˈneɪʃn/", "n. 幻觉", "hallucinate"),
        W("resilience", "/rɪˈzɪliəns/", "n. 韧性；恢复力", "resilient"),
        W("vulnerability", "/ˌvʌlnərəˈbɪləti/", "n. 脆弱性", "vulnerable"),
        W("self-esteem", "/ˌself ɪˈstiːm/", "n. 自尊", "esteem"),
        W("confidence", "/ˈkɑːnfɪdəns/", "n. 信心", "confident"),
        W("insecurity", "/ˌɪnsɪˈkjʊrəti/", "n. 不安全感", "insecure"),
        W("frustration", "/frʌˈstreɪʃn/", "n. 挫败感", "frustrate"),
        W("aggression", "/əˈɡreʃn/", "n. 攻击性", "aggressive"),
        W("hostility", "/hɑːˈstɪləti/", "n. 敌意", "hostile"),
        W("affection", "/əˈfekʃn/", "n. 喜爱", "affectionate"),
        W("alienation", "/ˌeɪliəˈneɪʃn/", "n. 疏离", "alienate"),
        W("conformity", "/kənˈfɔːrməti/", "n. 从众", "conform"),
        W("rebellion", "/rɪˈbeljən/", "n. 反抗", "rebel"),
        W("peer", "/pɪr/", "n. 同龄人", "peer pressure"),
        W("socialization", "/ˌsoʊʃələˈzeɪʃn/", "n. 社会化", "socialize"),
        W("conditioning", "/kənˈdɪʃənɪŋ/", "n. 条件反射", "condition"),
        W("reinforcement", "/ˌriːɪnˈfɔːrsmənt/", "n. 强化", "reinforce"),
        W("stimulus", "/ˈstɪmjələs/", "n. 刺激（pl. stimuli）", "stimulate"),
        W("response", "/rɪˈspɑːns/", "n. 反应", "respond"),
        W("attitude", "/ˈætɪtuːd/", "n. 态度", "attitudinal"),
        W("mindset", "/ˈmaɪndset/", "n. 思维模式", "mind + set"),
        W("bias", "/ˈbaɪəs/", "n. 偏见", "biased"),
        W("discrimination", "/dɪˌskrɪmɪˈneɪʃn/", "n. 歧视；辨别", "discriminate"),
        W("stigma", "/ˈstɪɡmə/", "n. 污名", "stigmatize"),
        W("counseling", "/ˈkaʊnsəlɪŋ/", "n. 心理咨询", "counsel"),
        W("therapy", "/ˈθerəpi/", "n. 治疗；疗法", "therapist"),
        W("psychotherapy", "/ˌsaɪkoʊˈθerəpi/", "n. 心理治疗", "psycho + therapy"),
        W("hypnosis", "/hɪpˈnoʊsɪs/", "n. 催眠", "hypnotize"),
        W("meditation", "/ˌmedɪˈteɪʃn/", "n. 冥想", "meditate"),
        W("mindfulness", "/ˈmaɪndfəlnəs/", "n. 正念", "mindful"),
        W("catharsis", "/kəˈθɑːrsɪs/", "n. 宣泄", "cathartic"),
        W("rationalize", "/ˈræʃnəlaɪz/", "v. 合理化（心理）", "rational"),
        W("rationalization", "/ˌræʃnələˈzeɪʃn/", "n. 合理化", "rationalize"),
        W("projection", "/prəˈdʒekʃn/", "n. 投射（心理）", "project"),
        W("denial", "/dɪˈnaɪəl/", "n. 否认（防御机制）", "deny"),
        W("repression", "/rɪˈpreʃn/", "n. 压抑", "repress"),
        W("sublimation", "/ˌsʌblɪˈmeɪʃn/", "n. 升华（心理）", "sublimate"),
        W("neurosis", "/nʊˈroʊsɪs/", "n. 神经症", "neurotic"),
        W("psychosis", "/saɪˈkoʊsɪs/", "n. 精神病", "psychotic"),
        W("disorder", "/dɪsˈɔːrdər/", "n. 紊乱；障碍", "order 反义"),
        W("syndrome", "/ˈsɪndroʊm/", "n. 综合征", "sym- + drom"),
        W("autism", "/ˈɔːtɪzəm/", "n. 自闭症", "autistic"),
        W("schizophrenia", "/ˌskɪtsəˈfriːniə/", "n. 精神分裂症", "schizo + phren"),
    ],
    [
        P("motivate sb to do", "/ˈmoʊtɪveɪt ˈsʌmbədi tə duː/", "激励某人做", "Teachers motivate students to read."),
        P("financial incentive", "/faɪˈnænʃl ɪnˈsentɪv/", "经济激励", "A financial incentive boosted sales."),
        P("racial prejudice", "/ˈreɪʃl ˈpredʒudɪs/", "种族偏见", "Fight racial prejudice openly."),
        P("on impulse", "/ɑːn ˈɪmpʌls/", "一时冲动", "He bought it on impulse."),
        P("peer pressure", "/pɪr ˈpreʃər/", "同辈压力", "Peer pressure shapes behavior."),
        P("self-esteem", "/ˌself ɪˈstiːm/", "自尊", "Praise can raise self-esteem."),
        P("coping mechanism", "/ˈkoʊpɪŋ ˈmekənɪzəm/", "应对机制", "Exercise is a coping mechanism."),
        P("mental health", "/ˈmentl helθ/", "心理健康", "Mental health matters at work."),
        P("anxiety disorder", "/æŋˈzaɪəti dɪsˈɔːrdər/", "焦虑症", "She sought help for anxiety disorder."),
        P("cognitive bias", "/ˈkɑːɡnətɪv ˈbaɪəs/", "认知偏差", "Cognitive bias affects judgment."),
        P("emotional intelligence", "/ɪˈmoʊʃənl ɪnˈtelɪdʒəns/", "情商", "Emotional intelligence aids leadership."),
        P("behavioral pattern", "/bɪˈheɪvjərəl ˈpætərn/", "行为模式", "Notice the behavioral pattern."),
        P("fight or flight", "/faɪt ɔːr flaɪt/", "战斗或逃跑反应", "Stress triggers fight or flight."),
        P("defense mechanism", "/dɪˈfens ˈmekənɪzəm/", "防御机制", "Denial is a defense mechanism."),
        P("positive reinforcement", "/ˈpɑːzətɪv ˌriːɪnˈfɔːrsmənt/", "正强化", "Use positive reinforcement in class."),
        P("negative reinforcement", "/ˈneɡətɪv ˌriːɪnˈfɔːrsmənt/", "负强化", "Negative reinforcement removes pain."),
        P("conditioned response", "/kənˈdɪʃənd rɪˈspɑːns/", "条件反射", "Salivation is a conditioned response."),
        P("loss of motivation", "/lɔːs əv ˌmoʊtɪˈveɪʃn/", "失去动力", "Burnout causes loss of motivation."),
        P("feel empathy for", "/fiːl ˈempəθi fɔːr/", "对…共情", "Feel empathy for victims."),
        P("show sympathy", "/ʃoʊ ˈsɪmpəθi/", "表示同情", "Show sympathy without pity."),
        P("overcome trauma", "/ˌoʊvərˈkʌm ˈtrɔːmə/", "克服创伤", "Therapy helps overcome trauma."),
        P("build resilience", "/bɪld rɪˈzɪliəns/", "培养韧性", "Sports build resilience."),
        P("social anxiety", "/ˈsoʊʃl æŋˈzaɪəti/", "社交焦虑", "Social anxiety limits networking."),
        P("panic attack", "/ˈpænɪk əˈtæk/", "恐慌发作", "She had a panic attack."),
        P("eating disorder", "/ˈiːtɪŋ dɪsˈɔːrdər/", "饮食障碍", "Media can trigger eating disorder."),
        P("addictive behavior", "/əˈdɪktɪv bɪˈheɪvjər/", "成瘾行为", "Gambling is addictive behavior."),
        P("withdrawal symptoms", "/wɪðˈdrɔːəl ˈsɪmptəmz/", "戒断症状", "Withdrawal symptoms appeared."),
        P("seek counseling", "/siːk ˈkaʊnsəlɪŋ/", "寻求咨询", "Seek counseling early."),
        P("undergo therapy", "/ˌʌndərˈɡoʊ ˈθerəpi/", "接受治疗", "He underwent therapy for months."),
        P("practice mindfulness", "/ˈpræktɪs ˈmaɪndfəlnəs/", "练习正念", "Practice mindfulness daily."),
        P("change one's mindset", "/tʃeɪndʒ wʌnz ˈmaɪndset/", "改变心态", "Coaching changed her mindset."),
        P("conform to norms", "/kənˈfɔːrm tə nɔːrmz/", " conform 规范", "Teens conform to norms."),
        P("rebel against authority", "/rɪˈbel əˈɡenst əˈθɔːrəti/", "反抗权威", "Youth rebel against authority."),
        P("gender stereotype", "/ˈdʒendər ˈsteriətaɪp/", "性别刻板印象", "Challenge gender stereotype."),
        P("implicit bias", "/ɪmˈplɪsɪt ˈbaɪəs/", "隐性偏见", "Training reduces implicit bias."),
        P("stigma around mental illness", "/ˈstɪɡmə əˈraʊnd ˈmentl ˈɪlnəs/", "对心理疾病的污名", "Reduce stigma around mental illness."),
        P("psychological well-being", "/ˌsaɪkəˈlɑːdʒɪkl ˌwel ˈbiːɪŋ/", "心理健康（福祉）", "Sleep aids psychological well-being."),
        P("intrinsic motivation", "/ɪnˈtrɪnzɪk ˌmoʊtɪˈveɪʃn/", "内在动机", "Curiosity drives intrinsic motivation."),
        P("extrinsic reward", "/ɪkˈstrɪnzɪk rɪˈwɔːrd/", "外在奖励", "Extrinsic reward fades quickly."),
        P("fight discrimination", "/faɪt dɪˌskrɪmɪˈneɪʃn/", "对抗歧视", "Laws fight discrimination."),
    ],
)

# Fix typo in Day 12 phrase
DAYS[-1]["phrases"][31] = P(
    "conform to norms",
    "/kənˈfɔːrm tə nɔːrmz/",
    "遵从规范",
    "Teens conform to norms.",
)

# ---------- Day 13 medi/scrib media ----------
add_day(
    DAYS,
    13,
    "媒体与信息 | medi / scrib / voc = 中间 / 写 / 声",
    [
        (
            "medi / scrib / voc",
            "中间 / 写 / 声音",
            [
                ("medi", "media, intermediate, Mediterranean, mediate"),
                ("scrib / script", "describe, manuscript, subscribe, prescription"),
                ("verb / voc", "verbal, vocabulary, advocate, vocation"),
                ("trans-", "transmit, translate, transparent, transfer"),
            ],
        )
    ],
    [
        W("media", "/ˈmiːdiə/", "n. 媒体（medium 复数）", "mass media"),
        W("transmit", "/trænsˈmɪt/", "v. 传输；传播", "trans- + mit"),
        W("circulate", "/ˈsɜːrkjuleɪt/", "v. 流通；传播", "circulation"),
        W("distort", "/dɪˈstɔːrt/", "v. 扭曲", "distortion"),
        W("exaggerate", "/ɪɡˈzædʒəreɪt/", "v. 夸张", "exaggeration"),
        W("authentic", "/ɔːˈθentɪk/", "a. 真实的；可信的", "authenticity"),
        W("bias", "/ˈbaɪəs/", "n. 偏见；倾向", "biased"),
        W("headline", "/ˈhedlaɪn/", "n. 头条", "head + line"),
        W("journalism", "/ˈdʒɜːrnəlɪzəm/", "n. 新闻业", "journalist"),
        W("journalist", "/ˈdʒɜːrnəlɪst/", "n. 记者", "journal"),
        W("editorial", "/ˌedɪˈtɔːriəl/", "n. 社论；a. 编辑的", "editor"),
        W("correspondent", "/ˌkɔːrəˈspɑːndənt/", "n. 通讯员", "correspond"),
        W("columnist", "/ˈkɑːləmnɪst/", "n. 专栏作家", "column"),
        W("broadcast", "/ˈbrɔːdkæst/", "v./n. 广播；播送", "broad + cast"),
        W("telecast", "/ˈtelikæst/", "v./n. 电视播送", "tele + cast"),
        W("podcast", "/ˈpɑːdkæst/", "n. 播客", "iPod + broadcast"),
        W("stream", "/striːm/", "v./n. 流媒体播放", "livestream"),
        W("viral", "/ˈvaɪrəl/", "a. 病毒式传播的", "go viral"),
        W("algorithm", "/ˈælɡərɪðəm/", "n. 算法", "algorithmic"),
        W("platform", "/ˈplætfɔːrm/", "n. 平台", "social platform"),
        W("subscriber", "/səbˈskraɪbər/", "n. 订阅者", "subscribe"),
        W("subscription", "/səbˈskrɪpʃn/", "n. 订阅", "subscribe"),
        W("manuscript", "/ˈmænjuskrɪpt/", "n. 手稿", "manu + script"),
        W("transcript", "/ˈtrænskrɪpt/", "n. 誊本；文字稿", "trans- + script"),
        W("inscription", "/ɪnˈskrɪpʃn/", "n. 铭文；题字", "in- + script"),
        W("prescription", "/prɪˈskrɪpʃn/", "n. 处方；规定", "pre- + script"),
        W("describe", "/dɪˈskraɪb/", "v. 描述", "de- + scrib"),
        W("description", "/dɪˈskrɪpʃn/", "n. 描述", "describe"),
        W("narrative", "/ˈnærətɪv/", "n. 叙事；a. 叙述的", "narrate"),
        W("commentary", "/ˈkɑːmənteri/", "n. 评论；解说", "comment"),
        W("coverage", "/ˈkʌvərɪdʒ/", "n. 报道范围", "cover"),
        W("publicity", "/pʌbˈlɪsəti/", "n. 宣传；曝光", "public"),
        W("propaganda", "/ˌprɑːpəˈɡændə/", "n. 宣传（贬义）", "propagate"),
        W("censorship", "/ˈsensərʃɪp/", "n. 审查制度", "censor"),
        W("disinformation", "/ˌdɪsɪnfərˈmeɪʃn/", "n. 虚假信息", "misinformation 近义"),
        W("misinformation", "/ˌmɪsɪnfərˈmeɪʃn/", "n. 错误信息", "mis- + information"),
        W("rumor", "/ˈruːmər/", "n. 谣言", "rumour BrE"),
        W("speculation", "/ˌspekjuˈleɪʃn/", "n. 推测；投机", "speculate"),
        W("sensational", "/senˈseɪʃənl/", "a. 耸人听闻的", "sensation"),
        W("tabloid", "/ˈtæblɔɪd/", "n. 小报", "tabloid press"),
        W("broadsheet", "/ˈbrɔːdʃiːt/", "n. 大开本严肃报纸", "broad + sheet"),
        W("caption", "/ˈkæpʃn/", "n. 说明文字；字幕", "capture"),
        W("subtitle", "/ˈsʌbtaɪtl/", "n. 字幕", "sub- + title"),
        W("footage", "/ˈfʊtɪdʒ/", "n. 影像片段", "foot"),
        W("documentary", "/ˌdɑːkjuˈmentri/", "n. 纪录片", "document"),
        W("interviewee", "/ˌɪntərvjuːˈiː/", "n. 受访者", "interview"),
        W("source", "/sɔːrs/", "n. 消息来源", "sourcing"),
        W("anonymous", "/əˈnɑːnɪməs/", "a. 匿名的", "anonymity"),
        W("confidential", "/ˌkɑːnfɪˈdenʃl/", "a. 机密的", "confidence"),
        W("leak", "/liːk/", "v./n. 泄露", "leakage"),
        W("whistleblower", "/ˈwɪslbloʊər/", "n. 吹哨人", "whistle + blow"),
        W("advocate", "/ˈædvəkeɪt/", "v. 倡导；n. 支持者", "ad- + voc"),
        W("verbal", "/ˈvɜːrbl/", "a. 口头的", "verb"),
        W("vocabulary", "/voʊˈkæbjəleri/", "n. 词汇", "voc"),
        W("articulate", "/ɑːrˈtɪkjuleɪt/", "v. 清晰表达", "articulation"),
        W("rhetoric", "/ˈretərɪk/", "n. 修辞；花言巧语", "rhetorical"),
        W("discourse", "/ˈdɪskɔːrs/", "n. 话语；论述", "discursive"),
        W("semantics", "/sɪˈmæntɪks/", "n. 语义学", "semantic"),
        W("connotation", "/ˌkɑːnəˈteɪʃn/", "n. 隐含意义", "connote"),
        W("denotation", "/ˌdiːnoʊˈteɪʃn/", "n. 字面意义", "denote"),
        W("metaphor", "/ˈmetəfər/", "n. 隐喻", "metaphorical"),
        W("analogy", "/əˈnælədʒi/", "n. 类比", "analogous"),
        W("paraphrase", "/ˈpærəfreɪz/", "v./n. 释义", "para + phrase"),
        W("summarize", "/ˈsʌməraɪz/", "v. 概括", "summary"),
        W("quote", "/kwoʊt/", "v./n. 引用", "quotation"),
        W("citation", "/saɪˈteɪʃn/", "n. 引文；引用", "cite"),
        W("plagiarism", "/ˈpleɪdʒərɪzəm/", "n. 剽窃", "plagiarize"),
        W("copyright", "/ˈkɑːpiraɪt/", "n. 版权", "copy + right"),
        W("trademark", "/ˈtreɪdmɑːrk/", "n. 商标", "trade + mark"),
        W("publication", "/ˌpʌblɪˈkeɪʃn/", "n. 出版；发表", "publish"),
        W("circulation", "/ˌsɜːrkjəˈleɪʃn/", "n. 发行量；流通", "circulate"),
        W("readership", "/ˈriːdərʃɪp/", "n. 读者群", "reader"),
        W("viewership", "/ˈvjuːərʃɪp/", "n. 观众群", "viewer"),
        W("engagement", "/ɪnˈɡeɪdʒmənt/", "n. 互动；参与度", "engage"),
        W("influencer", "/ˈɪnfluənsər/", "n. 网红；影响者", "influence"),
        W("virality", "/vaɪˈræləti/", "n. 病毒传播性", "viral"),
        W("clickbait", "/ˈklɪkbeɪt/", "n. 标题党", "click + bait"),
        W("echo chamber", "/ˈekoʊ ˈtʃeɪmbər/", "n. 信息茧房", "echo + chamber"),
        W("filter bubble", "/ˈfɪltər ˈbʌbl/", "n. 过滤气泡", "algorithmic"),
    ],
    [
        P("mass media", "/mæs ˈmiːdiə/", "大众传媒", "Influenced by mass media."),
        P("transmit information", "/trænsˈmɪt ˌɪnfərˈmeɪʃn/", "传递信息", "Transmit information quickly."),
        P("distort the truth", "/dɪˈstɔːrt ðə truːθ/", "歪曲真相", "Headlines distort the truth."),
        P("media bias", "/ˈmiːdiə ˈbaɪəs/", "媒体偏见", "Watch for media bias."),
        P("breaking news", "/ˈbreɪkɪŋ nuːz/", "突发新闻", "Breaking news interrupted the show."),
        P("front-page headline", "/frʌnt peɪdʒ ˈhedlaɪn/", "头版头条", "A front-page headline shocked readers."),
        P("live broadcast", "/laɪv ˈbrɔːdkæst/", "现场直播", "The trial had a live broadcast."),
        P("go viral", "/ɡoʊ ˈvaɪrəl/", "病毒式传播", "The clip went viral overnight."),
        P("social media platform", "/ˈsoʊʃl ˈmiːdiə ˈplætfɔːrm/", "社交媒体平台", "Regulate social media platform."),
        P("news coverage", "/nuːz ˈkʌvərɪdʒ/", "新闻报道", "News coverage was extensive."),
        P("press conference", "/pres ˈkɑːnfərəns/", "新闻发布会", "The CEO held a press conference."),
        P("anonymous source", "/əˈnɑːnɪməs sɔːrs/", "匿名消息源", "An anonymous source leaked files."),
        P("fact-check", "/fækt tʃek/", "事实核查", "Reporters fact-check claims."),
        P("spread misinformation", "/spred ˌmɪsɪnfərˈmeɪʃn/", "传播错误信息", "Bots spread misinformation."),
        P("combat disinformation", "/ˈkɑːmbæt ˌdɪsɪnfərˈmeɪʃn/", "打击虚假信息", "Governments combat disinformation."),
        P("freedom of the press", "/ˈfriːdəm əv ðə pres/", "新闻自由", "Freedom of the press is vital."),
        P("editorial opinion", "/ˌedɪˈtɔːriəl əˈpɪnjən/", "社论观点", "The editorial opinion divided readers."),
        P("investigative journalism", "/ɪnˈvestɪɡeɪtɪv ˈdʒɜːrnəlɪzəm/", "调查性报道", "Investigative journalism exposed fraud."),
        P("sensational headline", "/senˈseɪʃənl ˈhedlaɪn/", "耸动标题", "Avoid sensational headline."),
        P("quote out of context", "/kwoʊt aʊt əv ˈkɑːntekst/", "断章取义", "They quote out of context."),
        P("paraphrase a passage", "/ˈpærəfreɪz ə ˈpæsɪdʒ/", "释义段落", "Paraphrase a passage carefully."),
        P("avoid plagiarism", "/əˈvɔɪd ˈpleɪdʒərɪzəm/", "避免剽窃", "Cite sources to avoid plagiarism."),
        P("copyright infringement", "/ˈkɑːpiraɪt ɪnˈfrɪndʒmənt/", "侵犯版权", "Sued for copyright infringement."),
        P("audience engagement", "/ˈɔːdiəns ɪnˈɡeɪdʒmənt/", "受众互动", "Audience engagement rose sharply."),
        P("subscriber base", "/səbˈskraɪbər beɪs/", "订阅用户群", "The subscriber base doubled."),
        P("podcast episode", "/ˈpɑːdkæst ˈepɪsoʊd/", "播客单集", "Download the podcast episode."),
        P("documentary footage", "/ˌdɑːkjuˈmentri ˈfʊtɪdʒ/", "纪录片素材", "Archive documentary footage."),
        P("verbal communication", "/ˈvɜːrbl kəˌmjuːnɪˈkeɪʃn/", "口头交流", "Verbal communication skills matter."),
        P("rhetorical device", "/rɪˈtɔːrɪkl dɪˈvaɪs/", "修辞手法", "Metaphor is a rhetorical device."),
        P("political discourse", "/pəˈlɪtɪkl ˈdɪskɔːrs/", "政治话语", "Political discourse turned hostile."),
        P("negative connotation", "/ˈneɡətɪv ˌkɑːnəˈteɪʃn/", "负面含义", "The term has negative connotation."),
        P("public opinion", "/ˈpʌblɪk əˈpɪnjən/", "公众舆论", "Polls reflect public opinion."),
        P("media literacy", "/ˈmiːdiə ˈlɪtərəsi/", "媒介素养", "Teach media literacy in schools."),
        P("filter bubble effect", "/ˈfɪltər ˈbʌbl ɪˈfekt/", "过滤气泡效应", "Algorithms create filter bubble effect."),
        P("echo chamber effect", "/ˈekoʊ ˈtʃeɪmbər ɪˈfekt/", "回音室效应", "Debate suffers echo chamber effect."),
        P("clickbait title", "/ˈklɪkbeɪt ˈtaɪtl/", "标题党标题", "Reject clickbait title."),
        P("whistleblower protection", "/ˈwɪslbloʊər prəˈtekʃn/", "吹哨人保护", "Law ensures whistleblower protection."),
        P("confidential leak", "/ˌkɑːnfɪˈdenʃl liːk/", "机密泄露", "A confidential leak caused panic."),
        P("circulation decline", "/ˌsɜːrkjəˈleɪʃn dɪˈklaɪn/", "发行量下降", "Print saw circulation decline."),
        P("influence public debate", "/ˈɪnfluəns ˈpʌblɪk dɪˈbeɪt/", "影响公共讨论", "Media influence public debate."),
    ],
)

print("Building remaining days...")

