#!/usr/bin/env python3
"""One-shot builder for vocab_days_21_30.py — run once then delete."""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent

OUT = Path(__file__).with_name("vocab_days_21_30.py")


def W(word: str, ipa: str, gloss: str, tip: str = "") -> tuple:
    return (word, ipa, gloss, tip or "—")


def P(phrase: str, ipa: str, gloss: str, ex: str) -> tuple:
    return (phrase, ipa, gloss, ex)


DAYS: list[dict] = []


def add_day(
    n: int,
    title: str,
    roots: list[tuple[str, str, list[tuple[str, str]]]],
    words: list[tuple],
    phrases: list[tuple],
) -> None:
    words = list({w[0]: w for w in words}.values())[:80]
    phrases = list({p[0]: p for p in phrases}.values())[:40]
    assert len(words) == 80, f"Day {n}: {len(words)} words"
    assert len(phrases) == 40, f"Day {n}: {len(phrases)} phrases"
    DAYS.append({"n": n, "title": title, "roots": roots, "words": words, "phrases": phrases})


# ── Day 21: REVIEW mix 15–20 ──────────────────────────────────────────────
add_day(
    21,
    "复习（Day 15–20）| pos / contra / quant / chron / pot / eth 综合",
    [
        (
            "pos / contra / quant / chron / pot / eth",
            "放置 / 相反 / 量 / 时 / 能 / 伦理",
            [
                ("pos / pon", "propose, compose, expose, position"),
                ("contra / counter", "contrast, contrary, counterpart"),
                ("quant / magn / min", "quantity, magnitude, minority"),
                ("chron / temp / ced", "chronic, temporary, precede, proceed"),
                ("pot / fac / cap", "potential, competent, capable, efficient"),
                ("eth / norm / jud", "ethical, moral, norm, integrity"),
            ],
        )
    ],
    [
        W("propose", "/prəˈpoʊz/", "v. 提议；求婚", "pos"),
        W("proposal", "/prəˈpoʊzl/", "n. 提议；求婚", "propose"),
        W("expose", "/ɪkˈspoʊz/", "v. 暴露；揭露", "ex- + pos"),
        W("exposure", "/ɪkˈspoʊʒər/", "n. 暴露；曝光", "expose"),
        W("compose", "/kəmˈpoʊz/", "v. 组成；创作", "com- + pos"),
        W("composition", "/ˌkɑːmpəˈzɪʃn/", "n. 构成；作文", "compose"),
        W("illustrate", "/ˈɪləstreɪt/", "v. 说明；例证", "illus"),
        W("demonstrate", "/ˈdemənstreɪt/", "v. 证明；演示", "demo"),
        W("indicate", "/ˈɪndɪkeɪt/", "v. 表明；指示", "in- + dic"),
        W("imply", "/ɪmˈplaɪ/", "v. 暗示", "im- + ply"),
        W("implication", "/ˌɪmplɪˈkeɪʃn/", "n. 含义；牵连", "imply"),
        W("conclude", "/kənˈkluːd/", "v. 得出结论", "con- + clud"),
        W("conclusion", "/kənˈkluːʒn/", "n. 结论", "conclude"),
        W("contrast", "/ˈkɑːntræst/", "n. 对比", "contra"),
        W("contrary", "/ˈkɑːntreri/", "a. 相反的", "contra"),
        W("versus", "/ˈvɜːrsəs/", "prep. 对；相对", "vs."),
        W("whereas", "/ˌwerˈæz/", "conj. 然而；鉴于", "书面转折"),
        W("nevertheless", "/ˌnevərðəˈles/", "adv. 尽管如此", "never + less"),
        W("nonetheless", "/ˌnʌnðəˈles/", "adv. 尽管如此", "≈ nevertheless"),
        W("diverse", "/daɪˈvɜːrs/", "a. 多样的", "di- + vers"),
        W("diversity", "/daɪˈvɜːrsəti/", "n. 多样性", "diverse"),
        W("counterpart", "/ˈkaʊntərpɑːrt/", "n. 对应物", "counter + part"),
        W("counteract", "/ˌkaʊntərˈækt/", "v. 抵消", "counter + act"),
        W("quantity", "/ˈkwɑːntəti/", "n. 数量", "quant"),
        W("quantitative", "/ˈkwɑːntəteɪtɪv/", "a. 定量的", "quantity"),
        W("magnitude", "/ˈmæɡnɪtuːd/", "n. 重大；震级", "magn"),
        W("majority", "/məˈdʒɔːrəti/", "n. 多数", "major"),
        W("minority", "/maɪˈnɔːrəti/", "n. 少数", "minor"),
        W("proportion", "/prəˈpɔːrʃn/", "n. 比例", "portio"),
        W("approximate", "/əˈprɑːksɪmət/", "a. 近似的", "ad- + proxim"),
        W("abundant", "/əˈbʌndənt/", "a. 丰富的", "abund"),
        W("adequate", "/ˈædɪkwət/", "a. 足够的", "ad- + equ"),
        W("temporary", "/ˈtempəreri/", "a. 暂时的", "temp"),
        W("contemporary", "/kənˈtempəreri/", "a. 当代的", "con- + tempor"),
        W("chronic", "/ˈkrɑːnɪk/", "a. 慢性的；长期的", "chron"),
        W("precede", "/prɪˈsiːd/", "v. 先于", "pre- + cede"),
        W("proceed", "/prəˈsiːd/", "v. 继续进行", "pro- + ceed"),
        W("postpone", "/poʊˈspoʊn/", "v. 推迟", "post- + pone"),
        W("duration", "/duˈreɪʃn/", "n. 持续时间", "dure"),
        W("phase", "/feɪz/", "n. 阶段", "phase"),
        W("potential", "/pəˈtenʃl/", "a./n. 潜在的；潜力", "pot"),
        W("competent", "/ˈkɑːmpɪtənt/", "a. 胜任的", "compete"),
        W("competence", "/ˈkɑːmpɪtəns/", "n. 能力", "competent"),
        W("proficient", "/prəˈfɪʃnt/", "a. 熟练的", "pro- + fic"),
        W("proficiency", "/prəˈfɪʃnsi/", "n. 熟练", "proficient"),
        W("capable", "/ˈkeɪpəbl/", "a. 有能力的", "cap"),
        W("capacity", "/kəˈpæsəti/", "n. 能力；容量", "cap"),
        W("efficient", "/ɪˈfɪʃnt/", "a. 高效的", "fac"),
        W("efficiency", "/ɪˈfɪʃnsi/", "n. 效率", "efficient"),
        W("effective", "/ɪˈfektɪv/", "a. 有效的", "effect"),
        W("accomplish", "/əˈkɑːmplɪʃ/", "v. 完成", "ac- + compl"),
        W("accomplishment", "/əˈkɑːmplɪʃmənt/", "n. 成就", "accomplish"),
        W("excellence", "/ˈeksələns/", "n. 卓越", "excel"),
        W("ethical", "/ˈeθɪkl/", "a. 伦理的", "eth"),
        W("ethics", "/ˈeθɪks/", "n. 伦理学", "eth"),
        W("moral", "/ˈmɔːrəl/", "a. 道德的", "mor"),
        W("morality", "/məˈræləti/", "n. 道德", "moral"),
        W("norm", "/nɔːrm/", "n. 规范", "norm"),
        W("normal", "/ˈnɔːrml/", "a. 正常的", "norm"),
        W("principle", "/ˈprɪnsəpl/", "n. 原则", "princip"),
        W("obligation", "/ˌɑːblɪˈɡeɪʃn/", "n. 义务", "oblige"),
        W("integrity", "/ɪnˈteɡrəti/", "n. 正直；完整", "integr"),
        W("accountability", "/əˌkaʊntəˈbɪləti/", "n. 问责", "account"),
        W("violate", "/ˈvaɪəleɪt/", "v. 违反", "viol"),
        W("position", "/pəˈzɪʃn/", "n. 位置；立场", "pos"),
        W("posit", "/ˈpɑːzɪt/", "v. 假定（学术）", "pos"),
        W("postulate", "/ˈpɑːstʃəleɪt/", "v. 假定；公设", "post-"),
        W("suppose", "/səˈpoʊz/", "v. 假设；认为", "sub- + pos"),
        W("opposite", "/ˈɑːpəzɪt/", "a. 相反的", "op- + pos"),
        W("reverse", "/rɪˈvɜːrs/", "v./a. 反转；相反", "re- + vers"),
        W("convert", "/kənˈvɜːrt/", "v. 转换", "con- + vert"),
        W("diminish", "/dɪˈmɪnɪʃ/", "v. 减少", "min"),
        W("minimum", "/ˈmɪnɪməm/", "n. 最小值", "min"),
        W("maximum", "/ˈmæksɪməm/", "n. 最大值", "max"),
        W("synchronize", "/ˈsɪŋkrənaɪz/", "v. 同步", "syn + chron"),
        W("chronology", "/krəˈnɑːlədʒi/", "n. 年表；年代学", "chron"),
        W("process", "/ˈprɑːses/", "n. 过程", "pro- + cess"),
        W("access", "/ˈækses/", "n./v. 通道；访问", "ac- + cess"),
        W("success", "/səkˈses/", "n. 成功", "suc- + cess"),
        W("succeed", "/səkˈsiːd/", "v. 成功；接替", "suc- + ceed"),
        W("preliminary", "/prɪˈlɪmɪneri/", "a. 初步的", "pre- + limin"),
        W("simultaneous", "/ˌsaɪmlˈteɪniəs/", "a. 同时的", "simul"),
    ],
    [
        P("propose a solution", "/prəˈpoʊz ə səˈluːʃn/", "提出方案", "Propose a solution to the crisis."),
        P("expose sb to sth", "/ɪkˈspoʊz ˈsʌmbədi tə/", "使接触", "Expose children to art early."),
        P("as illustrated by", "/æz ˈɪləstreɪtɪd baɪ/", "如…所示", "As illustrated by the chart."),
        P("draw a conclusion", "/drɔː ə kənˈkluːʒn/", "得出结论", "Draw a conclusion from data."),
        P("in contrast to", "/ɪn ˈkɑːntræst tə/", "与…形成对比", "In contrast to last year."),
        P("on the contrary", "/ɑːn ðə ˈkɑːntreri/", "恰恰相反", "On the contrary, it improved."),
        P("diverse opinions", "/daɪˈvɜːrs əˈpɪnjənz/", "不同意见", "Diverse opinions emerged."),
        P("Chinese counterpart", "/ˌtʃaɪˈniːz ˈkaʊntərpɑːrt/", "中方对应机构", "Meet their Chinese counterpart."),
        P("a large proportion of", "/ə lɑːrdʒ prəˈpɔːrʃn əv/", "很大一部分", "A large proportion of users agree."),
        P("the vast majority", "/ðə væst məˈdʒɔːrəti/", "绝大多数", "The vast majority voted yes."),
        P("of great magnitude", "/əv ɡreɪt ˈmæɡnɪtuːd/", "规模巨大", "A disaster of great magnitude."),
        P("adequate supply", "/ˈædɪkwət səˈplaɪ/", "充足供应", "An adequate supply of water."),
        P("temporary measure", "/ˈtempəreri ˈmeʒər/", "临时措施", "A temporary measure was adopted."),
        P("contemporary society", "/kənˈtempəreri səˈsaɪəti/", "当代社会", "In contemporary society."),
        P("postpone until", "/poʊˈspoʊn ənˈtɪl/", "推迟到", "Postpone until next week."),
        P("for the duration of", "/fɔːr ðə duˈreɪʃn əv/", "在…期间", "For the duration of the trial."),
        P("potential risk", "/pəˈtenʃl rɪsk/", "潜在风险", "A potential risk remains."),
        P("be proficient in", "/bi prəˈfɪʃnt ɪn/", "精通", "Be proficient in English."),
        P("capable of", "/ˈkeɪpəbl əv/", "能够", "Capable of solving problems."),
        P("accomplish a goal", "/əˈkɑːmplɪʃ ə ɡoʊl/", "达成目标", "Accomplish a goal on time."),
        P("ethical standards", "/ˈeθɪkl ˈstændərdz/", "伦理标准", "Meet ethical standards."),
        P("social norms", "/ˈsoʊʃl nɔːrmz/", "社会规范", "Follow social norms."),
        P("moral obligation", "/ˈmɔːrəl ˌɑːblɪˈɡeɪʃn/", "道德义务", "A moral obligation to help."),
        P("violate the law", "/ˈvaɪəleɪt ðə lɔː/", "违法", "Violate the law knowingly."),
        P("demonstrate that", "/ˈdemənstreɪt ðæt/", "证明", "Demonstrate that it works."),
        P("indicate that", "/ˈɪndɪkeɪt ðæt/", "表明", "Data indicate that costs rose."),
        P("imply that", "/ɪmˈplaɪ ðæt/", "暗示", "His tone implied that he disagreed."),
        P("nevertheless important", "/ˌnevərðəˈles ɪmˈpɔːrtnt/", "仍然重要", "Nevertheless important for policy."),
        P("whereas previously", "/ˌwerˈæz ˈpriːviəsli/", "而此前", "Whereas previously it was rare."),
        P("efficient use of", "/ɪˈfɪʃnt juːs əv/", "高效利用", "Efficient use of resources."),
        P("effective measure", "/ɪˈfektɪv ˈmeʒər/", "有效措施", "An effective measure against fraud."),
        P("competent staff", "/ˈkɑːmpɪtənt stæf/", "胜任的员工", "Competent staff are essential."),
        P("abundant evidence", "/əˈbʌndənt ˈevɪdəns/", "充分证据", "Abundant evidence supports it."),
        P("approximate estimate", "/əˈprɑːksɪmət ˈestɪmət/", "大致估计", "An approximate estimate suffices."),
        P("chronic disease", "/ˈkrɑːnɪk dɪˈziːz/", "慢性病", "Chronic disease management."),
        P("precede the event", "/prɪˈsiːd ði ɪˈvent/", "先于事件", "Symptoms precede the event."),
        P("proceed with caution", "/prəˈsiːd wɪð ˈkɔːʃn/", "谨慎进行", "Proceed with caution."),
        P("accountability mechanism", "/əˌkaʊntəˈbɪləti ˈmekənɪzəm/", "问责机制", "An accountability mechanism."),
        P("integrity of data", "/ɪnˈteɡrəti əv ˈdeɪtə/", "数据完整性", "Protect integrity of data."),
        P("quantitative analysis", "/ˈkwɑːntəteɪtɪv əˈnæləsɪs/", "定量分析", "Quantitative analysis was used."),
    ],
)

# ── Day 22: cept/concept abstract thinking ──────────────────────────────────
add_day(
    22,
    "六级加难：抽象思维 | cept / ceiv / cip / capt = 拿取",
    [
        (
            "cept / ceiv / cip / capt",
            "拿、抓、取",
            [
                ("cept / ceiv", "concept, perceive, receive, conceive"),
                ("cip / capt", "anticipate, participate, capture, captive"),
                ("inter- / pre-", "intercept, interpret, precede, prejudice"),
                ("-ual / -ion", "conceptual, perception, conception"),
            ],
        )
    ],
    [
        W("concept", "/ˈkɑːnsept/", "n. 概念", "con- + cept"),
        W("conceptual", "/kənˈseptʃuəl/", "a. 概念的", "concept"),
        W("conception", "/kənˈsepʃn/", "n. 概念；构想", "conceive"),
        W("conceive", "/kənˈsiːv/", "v. 构想；怀孕", "con- + ceive"),
        W("perception", "/pərˈsepʃn/", "n. 感知；看法", "perceive"),
        W("perceive", "/pərˈsiːv/", "v. 察觉；认为", "per- + ceive"),
        W("perceptive", "/pərˈseptɪv/", "a. 敏锐的", "perceive"),
        W("assumption", "/əˈsʌmpʃn/", "n. 假定", "assume"),
        W("assume", "/əˈsuːm/", "v. 假定；承担", "ad- + sume"),
        W("hypothesis", "/haɪˈpɑːθəsɪs/", "n. 假设", "hypo + thesis"),
        W("hypothetical", "/ˌhaɪpəˈθetɪkl/", "a. 假设的", "hypothesis"),
        W("paradigm", "/ˈpærədaɪm/", "n. 范式", "paradigm shift"),
        W("abstract", "/ˈæbstrækt/", "a. 抽象的", "abs- + tract"),
        W("abstraction", "/æbˈstrækʃn/", "n. 抽象", "abstract"),
        W("concrete", "/ˈkɑːŋkriːt/", "a. 具体的", "反义 abstract"),
        W("empirical", "/ɪmˈpɪrɪkl/", "a. 实证的", "empiricism"),
        W("empiricism", "/ɪmˈpɪrɪsɪzəm/", "n. 经验主义", "empirical"),
        W("theoretical", "/ˌθiːəˈretɪkl/", "a. 理论的", "theory"),
        W("theory", "/ˈθɪri/", "n. 理论", "theoretical"),
        W("notion", "/ˈnoʊʃn/", "n. 概念；想法", "not"),
        W("premise", "/ˈpremɪs/", "n. 前提", "pre- + mis"),
        W("inference", "/ˈɪnfərəns/", "n. 推论", "infer"),
        W("infer", "/ɪnˈfɜːr/", "v. 推断", "in- + fer"),
        W("deduce", "/dɪˈduːs/", "v. 演绎；推断", "de- + duce"),
        W("deduction", "/dɪˈdʌkʃn/", "n. 演绎；扣除", "deduce"),
        W("induction", "/ɪnˈdʌkʃn/", "n. 归纳；感应", "induce"),
        W("generalization", "/ˌdʒenrələˈzeɪʃn/", "n. 概括", "generalize"),
        W("generalize", "/ˈdʒenrəlaɪz/", "v. 概括；推广", "general"),
        W("speculation", "/ˌspekjuˈleɪʃn/", "n. 推测", "speculate"),
        W("speculative", "/ˈspekjuleɪtɪv/", "a. 推测的", "speculate"),
        W("intuition", "/ˌɪntuˈɪʃn/", "n. 直觉", "intuit"),
        W("intuitive", "/ɪnˈtuːɪtɪv/", "a. 直觉的", "intuition"),
        W("cognitive", "/ˈkɑːɡnətɪv/", "a. 认知的", "cogn"),
        W("cognition", "/kɑːɡˈnɪʃn/", "n. 认知", "cogn"),
        W("mental", "/ˈmentl/", "a. 心理的；精神的", "mind"),
        W("intellectual", "/ˌɪntəˈlektʃuəl/", "a. 智力的", "intellect"),
        W("rational", "/ˈræʃnəl/", "a. 理性的", "ratio"),
        W("irrational", "/ɪˈræʃnəl/", "a. 非理性的", "ir- + rational"),
        W("logical", "/ˈlɑːdʒɪkl/", "a. 逻辑的", "logic"),
        W("coherent", "/koʊˈhɪrənt/", "a. 连贯的", "co- + her"),
        W("incoherent", "/ˌɪnkoʊˈhɪrənt/", "a. 不连贯的", "in- + coherent"),
        W("ambiguity", "/ˌæmbɪˈɡjuːəti/", "n. 歧义", "ambi- + ag"),
        W("misconception", "/ˌmɪsənˈsepʃn/", "n. 误解", "mis- + conception"),
        W("preconception", "/ˌpriːkənˈsepʃn/", "n. 成见", "pre- + conception"),
        W("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期", "anti- + cip"),
        W("anticipation", "/ænˌtɪsɪˈpeɪʃn/", "n. 预期", "anticipate"),
        W("participate", "/pɑːrˈtɪsɪpeɪt/", "v. 参与", "part + cip"),
        W("participant", "/pɑːrˈtɪsɪpənt/", "n. 参与者", "participate"),
        W("capture", "/ˈkæptʃər/", "v. 捕获；体现", "capt"),
        W("captive", "/ˈkæptɪv/", "n./a. 俘虏（的）", "capt"),
        W("intercept", "/ˌɪntərˈsept/", "v. 拦截", "inter- + cept"),
        W("interpret", "/ɪnˈtɜːrprɪt/", "v. 解释", "inter- + pret"),
        W("interpretation", "/ɪnˌtɜːrprɪˈteɪʃn/", "n. 解释", "interpret"),
        W("misinterpret", "/ˌmɪsɪnˈtɜːrprɪt/", "v. 误解", "mis- + interpret"),
        W("prejudice", "/ˈpredʒudɪs/", "n. 偏见", "pre- + jud"),
        W("bias", "/ˈbaɪəs/", "n. 偏见", "六级"),
        W("stereotype", "/ˈsteriətaɪp/", "n. 刻板印象", "stereo + type"),
        W("paradox", "/ˈpærədɑːks/", "n. 悖论", "para- + dox"),
        W("dilemma", "/dɪˈlemə/", "n. 两难", "di- + lemma"),
        W("contradiction", "/ˌkɑːntrəˈdɪkʃn/", "n. 矛盾", "contra + dict"),
        W("consistent", "/kənˈsɪstənt/", "a. 一致的", "con- + sist"),
        W("inconsistent", "/ˌɪnkənˈsɪstənt/", "a. 不一致的", "in- + consistent"),
        W("implicit", "/ɪmˈplɪsɪt/", "a. 含蓄的", "im- + plic"),
        W("explicit", "/ɪkˈsplɪsɪt/", "a. 明确的", "ex- + plic"),
        W("nuance", "/ˈnuːɑːns/", "n. 细微差别", "法语借词"),
        W("subtle", "/ˈsʌtl/", "a. 微妙的", "subtlety"),
        W("profound", "/prəˈfaʊnd/", "a. 深刻的", "pro- + found"),
        W("superficial", "/ˌsuːpərˈfɪʃl/", "a. 肤浅的", "super + fic"),
        W("philosophical", "/ˌfɪləˈsɑːfɪkl/", "a. 哲学的", "philosophy"),
        W("metaphysical", "/ˌmetəˈfɪzɪkl/", "a. 形而上学的", "meta + physic"),
        W("epistemology", "/ɪˌpɪstəˈmɑːlədʒi/", "n. 认识论", "episteme"),
        W("ontology", "/ɑːnˈtɑːlədʒi/", "n. 本体论", "ont"),
        W("axiom", "/ˈæksiəm/", "n. 公理", "axi"),
        W("theorem", "/ˈθiːərəm/", "n. 定理", "theo"),
        W("corollary", "/ˈkɔːrəleri/", "n. 推论；必然结果", "coroll"),
        W("analogy", "/əˈnælədʒi/", "n. 类比", "ana- + log"),
        W("metaphor", "/ˈmetəfɔːr/", "n. 隐喻", "meta + phor"),
        W("symbolic", "/sɪmˈbɑːlɪk/", "a. 象征的", "symbol"),
        W("representational", "/ˌreprɪzenˈteɪʃənl/", "a. 表征的", "represent"),
        W("framework", "/ˈfreɪmwɜːrk/", "n. 框架", "frame + work"),
        W("schema", "/ˈskiːmə/", "n. 图式", "scheme"),
    ],
    [
        P("abstract concept", "/ˈæbstrækt ˈkɑːnsept/", "抽象概念", "An abstract concept is hard to define."),
        P("working hypothesis", "/ˈwɜːrkɪŋ haɪˈpɑːθəsɪs/", "工作假设", "A working hypothesis guides research."),
        P("paradigm shift", "/ˈpærədaɪm ʃɪft/", "范式转变", "A paradigm shift occurred."),
        P("empirical evidence", "/ɪmˈpɪrɪkl ˈevɪdəns/", "实证证据", "Empirical evidence supports the claim."),
        P("theoretical model", "/ˌθiːəˈretɪkl ˈmɑːdl/", "理论模型", "A theoretical model was proposed."),
        P("on the premise that", "/ɑːn ðə ˈpremɪs ðæt/", "以…为前提", "On the premise that data are valid."),
        P("draw an inference", "/drɔː ən ˈɪnfərəns/", "作出推论", "Draw an inference from facts."),
        P("deduce from", "/dɪˈduːs frəm/", "从…演绎", "Deduce conclusions from axioms."),
        P("generalize from", "/ˈdʒenrəlaɪz frəm/", "从…概括", "Generalize from a sample."),
        P("pure speculation", "/pjʊr ˌspekjuˈleɪʃn/", "纯粹推测", "That is pure speculation."),
        P("cognitive process", "/ˈkɑːɡnətɪv ˈprɑːses/", "认知过程", "A complex cognitive process."),
        P("rational thinking", "/ˈræʃnəl ˈθɪŋkɪŋ/", "理性思维", "Rational thinking requires evidence."),
        P("logical consistency", "/ˈlɑːdʒɪkl kənˈsɪstənsi/", "逻辑一致", "Maintain logical consistency."),
        P("coherent argument", "/koʊˈhɪrənt ˈɑːrɡjumənt/", "连贯论证", "Build a coherent argument."),
        P("common misconception", "/ˈkɑːmən ˌmɪsənˈsepʃn/", "常见误解", "A common misconception persists."),
        P("anticipate the outcome", "/ænˈtɪsɪpeɪt ði ˈaʊtkʌm/", "预期结果", "Anticipate the outcome early."),
        P("participate in debate", "/pɑːrˈtɪsɪpeɪt ɪn dɪˈbeɪt/", "参与辩论", "Participate in academic debate."),
        P("capture the essence", "/ˈkæptʃər ði ˈesns/", "抓住本质", "Capture the essence of the idea."),
        P("interpret the results", "/ɪnˈtɜːrprɪt ðə rɪˈzʌlts/", "解读结果", "Interpret the results cautiously."),
        P("implicit assumption", "/ɪmˈplɪsɪt əˈsʌmpʃn/", "隐含假定", "An implicit assumption underlies it."),
        P("explicit statement", "/ɪkˈsplɪsɪt ˈsteɪtmənt/", "明确陈述", "Make an explicit statement."),
        P("subtle distinction", "/ˈsʌtl dɪˈstɪŋkʃn/", "细微区别", "A subtle distinction matters."),
        P("profound insight", "/prəˈfaʊnd ˈɪnsaɪt/", "深刻洞见", "Offer a profound insight."),
        P("philosophical question", "/ˌfɪləˈsɑːfɪkl ˈkwestʃən/", "哲学问题", "Raise a philosophical question."),
        P("by analogy", "/baɪ əˈnælədʒi/", "通过类比", "Explain by analogy."),
        P("metaphor for", "/ˈmetəfɔːr fɔːr/", "…的隐喻", "A metaphor for change."),
        P("conceptual framework", "/kənˈseptʃuəl ˈfreɪmwɜːrk/", "概念框架", "A conceptual framework helps."),
        P("test the hypothesis", "/test ðə haɪˈpɑːθəsɪs/", "检验假设", "Test the hypothesis rigorously."),
        P("contradictory evidence", "/ˌkɑːntrəˈdɪktəri ˈevɪdəns/", "矛盾证据", "Contradictory evidence appeared."),
        P("intellectual rigor", "/ˌɪntəˈlektʃuəl ˈrɪɡər/", "学术严谨", "Intellectual rigor is required."),
        P("mental model", "/ˈmentl ˈmɑːdl/", "心智模型", "Update your mental model."),
        P("beyond perception", "/bɪˈjɑːnd pərˈsepʃn/", "超出感知", "Beyond ordinary perception."),
        P("form a conception", "/fɔːrm ə kənˈsepʃn/", "形成概念", "Form a conception of justice."),
        P("abstract reasoning", "/ˈæbstrækt ˈriːzənɪŋ/", "抽象推理", "Abstract reasoning skills."),
        P("concrete example", "/ˈkɑːŋkriːt ɪɡˈzæmpl/", "具体例子", "Give a concrete example."),
        P("nuance of meaning", "/ˈnuːɑːns əv ˈmiːnɪŋ/", "意义细微差别", "The nuance of meaning matters."),
        P("paradoxical situation", "/ˌpærəˈdɑːksɪkl ˌsɪtʃuˈeɪʃn/", "悖论情境", "A paradoxical situation arose."),
        P("moral dilemma", "/ˈmɔːrəl dɪˈlemə/", "道德两难", "Face a moral dilemma."),
        P("stereotypical view", "/ˌsteriəˈtɪpɪkl vjuː/", "刻板看法", "Challenge stereotypical views."),
        P("symbolic representation", "/sɪmˈbɑːlɪk ˌreprɪzenˈteɪʃn/", "象征表征", "Symbolic representation in art."),
    ],
)

# Continue with days 23-30 in the same file...
# Due to length, I'll append remaining days

exec(open(__file__).read().split("# BUILDER_PART2")[1].split("# END_BUILDER")[0]) if False else None
