#!/usr/bin/env python3
"""One-shot generator for vocab_days_1_10.py — run then delete if desired."""
from __future__ import annotations

# Each entry: (word, ipa, gloss, tip)
# gloss = Chinese with part of speech; tip = root hint or "—"

def day1_words():
    return [
        ("acquire", "/əˈkwaɪər/", "v. 获得；习得", "ac- + quire 寻求"),
        ("cognitive", "/ˈkɑːɡnətɪv/", "a. 认知的", "cogn + -itive"),
        ("comprehend", "/ˌkɑːmprɪˈhend/", "v. 理解", "com- + prehend 抓"),
        ("conscious", "/ˈkɑːnʃəs/", "a. 有意识的", "con- + sci + -ous"),
        ("perceive", "/pərˈsiːv/", "v. 察觉；认为", "per- + ceive"),
        ("retain", "/rɪˈteɪn/", "v. 保留；记住", "re- + tain"),
        ("assimilate", "/əˈsɪməleɪt/", "v. 吸收；同化", "as- + simil 同"),
        ("insight", "/ˈɪnsaɪt/", "n. 洞察", "in + sight"),
        ("recognize", "/ˈrekəɡnaɪz/", "v. 认出；承认", "re- + cogn + -ize"),
        ("cognition", "/kɑːɡˈnɪʃn/", "n. 认知", "cogn + -ition"),
        ("scientific", "/ˌsaɪənˈtɪfɪk/", "a. 科学的", "sci + -ific"),
        ("discipline", "/ˈdɪsəplɪn/", "n. 学科；纪律", "—"),
        ("curriculum", "/kəˈrɪkjələm/", "n. 课程", "—"),
        ("literacy", "/ˈlɪtərəsi/", "n. 读写能力", "liter 文字"),
        ("proficiency", "/prəˈfɪʃnsi/", "n. 熟练", "pro- + fic 做"),
        ("competence", "/ˈkɑːmpɪtəns/", "n. 能力", "compete 竞争"),
        ("memorize", "/ˈmeməraɪz/", "v. 记忆", "memory + -ize"),
        ("recall", "/rɪˈkɔːl/", "v. 回忆；召回", "re- + call"),
        ("grasp", "/ɡræsp/", "v.  grasp 理解；抓住", "—"),
        ("interpret", "/ɪnˈtɜːrprət/", "v. 解释；口译", "inter- + pret"),
        ("deduce", "/dɪˈduːs/", "v. 演绎；推断", "de- + duc 引"),
        ("infer", "/ɪnˈfɜːr/", "v. 推断", "in- + fer 带"),
        ("hypothesis", "/haɪˈpɑːθəsɪs/", "n. 假设", "hypo- + thesis"),
        ("theorem", "/ˈθiːərəm/", "n. 定理", "theo 神/理"),
        ("empirical", "/ɪmˈpɪrɪkl/", "a. 经验的；实证的", "empir 经验"),
        ("analytical", "/ˌænəˈlɪtɪkl/", "a. 分析的", "analysis"),
        ("synthesis", "/ˈsɪnθəsɪs/", "n. 综合", "syn- + thesis"),
        ("abstract", "/ˈæbstrækt/", "a. 抽象的", "abs- + tract 拉"),
        ("concrete", "/ˈkɑːŋkriːt/", "a. 具体的", "con- + cret"),
        ("concept", "/ˈkɑːnsept/", "n. 概念", "con- + cept 取"),
        ("notion", "/ˈnoʊʃn/", "n. 观念", "—"),
        ("intuition", "/ˌɪntuˈɪʃn/", "n. 直觉", "in- + tu 看"),
        ("awareness", "/əˈwernəs/", "a. 意识；觉察", "aware + -ness"),
        ("mindset", "/ˈmaɪndset/", "n. 思维模式", "—"),
        ("aptitude", "/ˈæptɪtuːd/", "n. 天资； aptitude", "apt 适合"),
        ("intelligence", "/ɪnˈtelɪdʒəns/", "n. 智力", "intel 之间"),
        ("wisdom", "/ˈwɪzdəm/", "n. 智慧", "wise + -dom"),
        ("knowledge", "/ˈnɑːlɪdʒ/", "n. 知识", "know + -ledge"),
        ("expertise", "/ˌekspɜːrˈtiːz/", "n. 专长", "expert + -ise"),
        ("scholar", "/ˈskɑːlər/", "n. 学者", "schol 学校"),
        ("academic", "/ˌækəˈdemɪk/", "a. 学术的", "academy"),
        ("intellectual", "/ˌɪntəˈlektʃuəl/", "a. 智力的；n. 知识分子", "intellect"),
        ("enlighten", "/ɪnˈlaɪtn/", "v. 启发；启蒙", "en- + light"),
        ("educate", "/ˈedʒukeɪt/", "v. 教育", "e- + duc 引"),
        ("instruct", "/ɪnˈstrʌkt/", "v. 指导；讲授", "in- + struct 建"),
        ("tutor", "/ˈtuːtər/", "v./n. 辅导", "—"),
        ("mentor", "/ˈmentɔːr/", "n. 导师", "—"),
        ("pedagogy", "/ˈpedəɡɑːdʒi/", "n. 教学法", "ped 儿童"),
        ("seminar", "/ˈsemɪnɑːr/", "n. 研讨会", "—"),
        ("lecture", "/ˈlektʃər/", "n./v. 讲座", "lect 读"),
        ("textbook", "/ˈtekstbʊk/", "n. 教科书", "—"),
        ("handout", "/ˈhændaʊt/", "n. 讲义", "—"),
        ("assignment", "/əˈsaɪnmənt/", "n. 作业；任务", "assign"),
        ("revision", "/rɪˈvɪʒn/", "n. 复习；修订", "re- + vis 看"),
        ("review", "/rɪˈvjuː/", "v./n. 复习；评论", "re- + view"),
        ("preview", "/ˈpriːvjuː/", "v./n. 预习", "pre- + view"),
        ("digest", "/daɪˈdʒest/", "v. 消化；领会", "di- + gest"),
        ("absorb", "/əbˈzɔːrb/", "v. 吸收", "ab- + sorb"),
        ("internalize", "/ɪnˈtɜːrnəlaɪz/", "v. 内化", "internal + -ize"),
        ("master", "/ˈmæstər/", "v. 掌握", "—"),
        ("practice", "/ˈpræktɪs/", "n./v. 练习", "pract 做"),
        ("rehearse", "/rɪˈhɜːrs/", "v. 排练；预演", "re- + hearse"),
        ("drill", "/drɪl/", "n./v.  drill 操练", "—"),
        ("reinforce", "/ˌriːɪnˈfɔːrs/", "v. 强化", "re- + in + force"),
        ("consolidate", "/kənˈsɑːlɪdeɪt/", "v. 巩固", "con- + solid"),
        ("forget", "/fərˈɡet/", "v. 忘记", "—"),
        ("oblivion", "/əˈblɪviən/", "n. 遗忘", "ob- + liv"),
        ("distract", "/dɪˈstrækt/", "v. 分心", "dis- + tract"),
        ("concentrate", "/ˈkɑːnsntreɪt/", "v. 集中", "con- + centr"),
        ("focus", "/ˈfoʊkəs/", "v./n. 聚焦", "—"),
        ("attentive", "/əˈtentɪv/", "a. 专心的", "attend"),
        ("diligent", "/ˈdɪlɪdʒənt/", "a. 勤奋的", "—"),
        ("persistent", "/pərˈsɪstənt/", "a. 坚持不懈的", "per- + sist"),
        ("motivation", "/ˌmoʊtɪˈveɪʃn/", "n. 动机", "motive"),
        ("curiosity", "/ˌkjʊriˈɑːsəti/", "n. 好奇心", "curious"),
        ("inquiry", "/ɪnˈkwaɪəri/", "n. 探究", "in- + quire"),
        ("explore", "/ɪkˈsplɔːr/", "v. 探索", "ex- + plor"),
        ("investigate", "/ɪnˈvestɪɡeɪt/", "v. 调查", "in- + vestig"),
        ("observe", "/əbˈzɜːrv/", "v. 观察", "ob- + serv"),
        ("experiment", "/ɪkˈsperɪmənt/", "n. 实验", "ex- + per 试"),
        ("demonstrate", "/ˈdemənstreɪt/", "v. 演示；证明", "de- + monstr"),
    ]


def day1_phrases():
    return [
        ("acquire a skill", "/əˈkwaɪər ə skɪl/", "掌握一项技能", "She acquired a skill in coding."),
        ("be conscious of", "/bi ˈkɑːnʃəs əv/", "意识到", "Be conscious of your bias."),
        ("gain insight into", "/ɡeɪn ˈɪnsaɪt ˈɪntuː/", "深入了解", "Gain insight into memory."),
        ("beyond comprehension", "/bɪˈjɑːnd ˌkɑːmprɪˈhenʃn/", "无法理解", "The scale is beyond comprehension."),
        ("retain information", "/rɪˈteɪn ˌɪnfərˈmeɪʃn/", "记住信息", "Sleep helps retain information."),
        ("assimilate knowledge", "/əˈsɪməleɪt ˈnɑːlɪdʒ/", "吸收知识", "Students assimilate knowledge slowly."),
        ("perceive a difference", "/pərˈsiːv ə ˈdɪfrəns/", "察觉差异", "Can you perceive a difference?"),
        ("cognitive ability", "/ˈkɑːɡnətɪv əˈbɪləti/", "认知能力", "Cognitive ability varies widely."),
        ("scientific method", "/ˌsaɪənˈtɪfɪk ˈmeθəd/", "科学方法", "Follow the scientific method."),
        ("develop proficiency", "/dɪˈveləp prəˈfɪʃnsi/", "提高熟练度", "Develop proficiency through practice."),
        ("grasp the concept", "/ɡræsp ðə ˈkɑːnsept/", "理解概念", "It took time to grasp the concept."),
        ("draw an inference", "/drɔː ən ˈɪnfərəns/", "作出推断", "We can draw an inference from data."),
        ("test a hypothesis", "/test ə haɪˈpɑːθəsɪs/", "检验假设", "Scientists test a hypothesis rigorously."),
        ("empirical evidence", "/ɪmˈpɪrɪkl ˈevɪdəns/", "实证证据", "Empirical evidence supports the claim."),
        ("abstract thinking", "/ˈæbstrækt ˈθɪŋkɪŋ/", "抽象思维", "Abstract thinking develops with age."),
        ("critical thinking", "/ˈkrɪtɪkl ˈθɪŋkɪŋ/", "批判性思维", "Schools teach critical thinking."),
        ("intellectual curiosity", "/ˌɪntəˈlektʃuəl ˌkjʊriˈɑːsəti/", "求知欲", "Intellectual curiosity drives research."),
        ("academic achievement", "/ˌækəˈdemɪk əˈtʃiːvmənt/", "学业成就", "Hard work boosts academic achievement."),
        ("enlighten the mind", "/ɪnˈlaɪtn ðə maɪnd/", "启迪心智", "Books enlighten the mind."),
        ("receive instruction", "/rɪˈsiːv ɪnˈstrʌkʃn/", "接受指导", "Students receive instruction online."),
        ("complete an assignment", "/kəmˈpliːt ən əˈsaɪnmənt/", "完成作业", "Complete an assignment on time."),
        ("review for an exam", "/rɪˈvjuː fɔːr ən ɪɡˈzæm/", "复习迎考", "Review for an exam every night."),
        ("internalize a lesson", "/ɪnˈtɜːrnəlaɪz ə ˈlesn/", "内化一课", "Children internalize a lesson through play."),
        ("master a subject", "/ˈmæstər ə ˈsʌbdʒɪkt/", "精通一门学科", "She mastered a subject in two years."),
        ("practice makes perfect", "/ˈpræktɪs meɪks ˈpɜːrfɪkt/", "熟能生巧", "Practice makes perfect."),
        ("reinforce learning", "/ˌriːɪnˈfɔːrs ˈlɜːrnɪŋ/", "强化学习", "Quizzes reinforce learning."),
        ("consolidate memory", "/kənˈsɑːlɪdeɪt ˈmeməri/", "巩固记忆", "Sleep helps consolidate memory."),
        ("lose concentration", "/luːz ˌkɑːnsnˈtreɪʃn/", "失去专注", "Noise makes you lose concentration."),
        ("stay focused", "/steɪ ˈfoʊkəst/", "保持专注", "Stay focused during lectures."),
        ("pay attention to", "/peɪ əˈtenʃn tə/", "注意", "Pay attention to details."),
        ("a thirst for knowledge", "/ə θɜːrst fɔːr ˈnɑːlɪdʒ/", "求知欲", "He has a thirst for knowledge."),
        ("conduct an experiment", "/kənˈdʌkt ən ɪkˈsperɪmənt/", "做实验", "Conduct an experiment safely."),
        ("observe carefully", "/əbˈzɜːrv ˈkerfəli/", "仔细观察", "Observe carefully before concluding."),
        ("investigate a problem", "/ɪnˈvestɪɡeɪt ə ˈprɑːbləm/", "调查问题", "Investigate a problem thoroughly."),
        ("explore new ideas", "/ɪkˈsplɔːr nuː aɪˈdiːəz/", "探索新想法", "Teams explore new ideas weekly."),
        ("learn by rote", "/lɜːrn baɪ roʊt/", "死记硬背", "Don't just learn by rote."),
        ("hands-on learning", "/hændz ɑːn ˈlɜːrnɪŋ/", "体验式学习", "Hands-on learning works best."),
        ("lifelong learning", "/ˈlaɪflɔːŋ ˈlɜːrnɪŋ/", "终身学习", "Lifelong learning is essential."),
        ("study habit", "/ˈstʌdi ˈhæbɪt/", "学习习惯", "Good study habits matter."),
        ("expand one's horizons", "/ɪkˈspænd wʌnz həˈraɪznz/", "开阔眼界", "Travel expands one's horizons."),
    ]


def day2_words():
    return [
        ("assert", "/əˈsɜːrt/", "v. 断言；维护", "—"),
        ("contend", "/kənˈtend/", "v. 主张；竞争", "—"),
        ("contradict", "/ˌkɑːntrəˈdɪkt/", "v. 反驳", "contra- + dict"),
        ("justify", "/ˈdʒʌstɪfaɪ/", "v. 证明正当", "just + -ify"),
        ("objective", "/əbˈdʒektɪv/", "a. 客观的；n. 目标", "object + -ive"),
        ("perspective", "/pərˈspektɪv/", "n. 视角", "per- + spect"),
        ("speculate", "/ˈspekjuleɪt/", "v. 推测", "spec 看"),
        ("valid", "/ˈvælɪd/", "a. 有效的", "—"),
        ("argument", "/ˈɑːrɡjumənt/", "n. 论点；争论", "—"),
        ("debate", "/dɪˈbeɪt/", "n./v. 辩论", "de- + bat"),
        ("dispute", "/dɪˈspjuːt/", "n./v. 争端", "dis- + put"),
        ("claim", "/kleɪm/", "v./n. 声称；索赔", "claim 喊"),
        ("proclaim", "/proʊˈkleɪm/", "v. 宣告", "pro- + claim"),
        ("exclaim", "/ɪkˈskleɪm/", "v.  exclaim 惊叫", "ex- + claim"),
        ("reclaim", "/rɪˈkleɪm/", "v.  reclaim 收回", "re- + claim"),
        ("predict", "/prɪˈdɪkt/", "v. 预测", "pre- + dict"),
        ("dictate", "/ˈdɪkteɪt/", "v.  dict 口述；支配", "dict"),
        ("verdict", "/ˈvɜːrdɪkt/", "n. 裁决", "ver- + dict"),
        ("contradiction", "/ˌkɑːntrəˈdɪkʃn/", "n. 矛盾", "contradict"),
        ("indict", "/ɪnˈdaɪt/", "v. 起诉", "in- + dict"),
        ("advocate", "/ˈædvəkeɪt/", "v. 倡导", "ad- + voc"),
        ("allege", "/əˈledʒ/", "v.  alleged 声称", "—"),
        ("maintain", "/meɪnˈteɪn/", "v. 坚持；维护", "main + tain"),
        ("refute", "/rɪˈfjuːt/", "v.  refute 驳斥", "—"),
        ("rebut", "/rɪˈbʌt/", "v.  rebut 反驳", "re- + but"),
        ("deny", "/dɪˈnaɪ/", "v. 否认", "de- + ny"),
        ("acknowledge", "/əkˈnɑːlɪdʒ/", "v. 承认", "—"),
        ("concede", "/kənˈsiːd/", "v.  concede 让步", "con- + cede"),
        ("confess", "/kənˈfes/", "v.  confess 供认", "con- + fess"),
        ("testify", "/ˈtestɪfaɪ/", "v.  testify 作证", "test + -ify"),
        ("witness", "/ˈwɪtnəs/", "n./v. 证人；目击", "—"),
        ("evidence", "/ˈevɪdəns/", "n. 证据", "e- + vid 看"),
        ("proof", "/pruːf/", "n. 证明", "—"),
        ("premise", "/ˈpremɪs/", "n. 前提", "pre- + mis"),
        ("conclusion", "/kənˈkluːʒn/", "n. 结论", "con- + clud"),
        ("inference", "/ˈɪnfərəns/", "n. 推论", "infer"),
        ("assumption", "/əˈsʌmpʃn/", "n. 假设", "assume"),
        ("proposition", "/ˌprɑːpəˈzɪʃn/", "n. 命题；提议", "pro- + pos"),
        ("thesis", "/ˈθiːsɪs/", "n. 论文；论点", "—"),
        ("stance", "/stæns/", "n. 立场", "—"),
        ("viewpoint", "/ˈvjuːpɔɪnt/", "n. 观点", "view + point"),
        ("standpoint", "/ˈstændpɔɪnt/", "n.  standpoint 立场", "—"),
        ("opinion", "/əˈpɪnjən/", "n. 意见", "—"),
        ("belief", "/bɪˈliːf/", "n. 信念", "believe"),
        ("conviction", "/kənˈvɪkʃn/", "n.  conviction 信念", "convict"),
        ("bias", "/ˈbaɪəs/", "n. 偏见", "—"),
        ("prejudice", "/ˈpredʒudɪs/", "n. 偏见", "pre- + jud"),
        ("subjective", "/səbˈdʒektɪv/", "a. 主观的", "sub- + ject"),
        ("neutral", "/ˈnuːtrəl/", "a. 中立的", "—"),
        ("impartial", "/ɪmˈpɑːrʃl/", "a. 公正的", "im- + partial"),
        ("rational", "/ˈræʃnəl/", "a. 理性的", "ratio 比"),
        ("logical", "/ˈlɑːdʒɪkl/", "a. 逻辑的", "logic"),
        ("coherent", "/koʊˈhɪrənt/", "a. 连贯的", "co- + her"),
        ("consistent", "/kənˈsɪstənt/", "a. 一致的", "con- + sist"),
        ("fallacy", "/ˈfæləsi/", "n. 谬误", "fall 错"),
        ("paradox", "/ˈpærədɑːks/", "n. 悖论", "para- + dox"),
        ("dilemma", "/dɪˈlemə/", "n. 两难", "di- + lemma"),
        ("controversy", "/ˈkɑːntrəvɜːrsi/", "n. 争议", "contra- + vers"),
        ("disagreement", "/ˌdɪsəˈɡriːmənt/", "n. 分歧", "dis- + agree"),
        ("consensus", "/kənˈsensəs/", "n. 共识", "con- + sens"),
        ("compromise", "/ˈkɑːmprəmaɪz/", "n./v. 妥协", "com- + promise"),
        ("negotiate", "/nɪˈɡoʊʃieɪt/", "v. 谈判", "neg 否"),
        ("persuade", "/pərˈsweɪd/", "v. 说服", "per- + suade"),
        ("convince", "/kənˈvɪns/", "v. 使信服", "con- + vinc"),
        ("rhetoric", "/ˈretərɪk/", "n. 修辞", "—"),
        ("eloquent", "/ˈeləkwənt/", "a. 雄辩的", "e- + loqu"),
        ("articulate", "/ɑːrˈtɪkjuleɪt/", "a.  articulate 表达清晰", "—"),
        ("emphasize", "/ˈemfəsaɪz/", "v. 强调", "—"),
        ("highlight", "/ˈhaɪlaɪt/", "v. 突出", "—"),
        ("illustrate", "/ˈɪləstreɪt/", "v. 说明", "—"),
        ("demonstrate", "/ˈdemənstreɪt/", "v. 论证", "—"),
        ("substantiate", "/səbˈstænʃieɪt/", "v.  substantiate 证实", "sub- + stant"),
        ("corroborate", "/kəˈrɑːbəreɪt/", "v.  corroborate  corroborate", "—"),
        ("undermine", "/ˌʌndərˈmaɪn/", "v. 削弱论点", "—"),
        ("overstate", "/ˌoʊvərˈsteɪt/", "v. 夸大", "over + state"),
        ("exaggerate", "/ɪɡˈzædʒəreɪt/", "v. 夸张", "—"),
        ("distort", "/dɪˈstɔːrt/", "v. 歪曲", "dis- + tort"),
        ("misinterpret", "/ˌmɪsɪnˈtɜːrprət/", "v. 误读", "mis- + interpret"),
        ("ambiguity", "/ˌæmbɪˈɡjuːəti/", "n. 歧义", "ambi- + gu"),
        ("nuance", "/ˈnuːɑːns/", "n. 细微差别", "—"),
        ("implication", "/ˌɪmplɪˈkeɪʃn/", "n. 含义；暗示", "imply"),
        ("counterargument", "/ˈkaʊntərˌɑːrɡjumənt/", "n.  counterargument", "counter + argument"),
    ]


def day2_phrases():
    return [
        ("from my perspective", "/frəm maɪ pərˈspektɪv/", "依我之见", "From my perspective, it's weak."),
        ("contradict oneself", "/ˌkɑːntrəˈdɪkt wʌnˈself/", "自相矛盾", "Don't contradict yourself."),
        ("justify one's action", "/ˈdʒʌstɪfaɪ wʌnz ˈækʃn/", "为行为辩护", "Justify your action."),
        ("a valid argument", "/ə ˈvælɪd ˈɑːrɡjumənt/", "站得住的论点", "That's a valid argument."),
        ("make a claim", "/meɪk ə kleɪm/", "提出主张", "Scientists make a claim cautiously."),
        ("present evidence", "/prɪˈzent ˈevɪdəns/", "出示证据", "Present evidence in court."),
        ("draw a conclusion", "/drɔː ə kənˈkluːʒn/", "得出结论", "Draw a conclusion from facts."),
        ("based on the premise", "/beɪst ɑːn ðə ˈpremɪs/", "基于前提", "Based on the premise, it follows."),
        ("take a stance", "/teɪk ə stæns/", "表明立场", "Take a stance on the issue."),
        ("hold an opinion", "/hoʊld ən əˈpɪnjən/", "持有观点", "Everyone may hold an opinion."),
        ("personal bias", "/ˈpɜːrsənl ˈbaɪəs/", "个人偏见", "Watch for personal bias."),
        ("remain neutral", "/rɪˈmeɪn ˈnuːtrəl/", "保持中立", "Judges must remain neutral."),
        ("a logical fallacy", "/ə ˈlɑːdʒɪkl ˈfæləsi/", "逻辑谬误", "That's a logical fallacy."),
        ("spark controversy", "/spɑːrk ˈkɑːntrəvɜːrsi/", "引发争议", "The film sparked controversy."),
        ("reach a consensus", "/riːtʃ ə kənˈsensəs/", "达成共识", "They reached a consensus."),
        ("reach a compromise", "/riːtʃ ə ˈkɑːmprəmaɪz/", "达成妥协", "Negotiators reached a compromise."),
        ("persuade sb of", "/pərˈsweɪd ˈsʌmbədi əv/", "使某人信服", "Persuade him of the truth."),
        ("convince sb that", "/kənˈvɪns ˈsʌmbədi ðæt/", "使某人相信", "Convince her that it matters."),
        ("make one's case", "/meɪk wʌnz keɪs/", "陈述理由", "Lawyers make their case."),
        ("state clearly", "/steɪt ˈklɪrli/", "清楚陈述", "State clearly what you mean."),
        ("put forward a proposal", "/pʊt ˈfɔːrwərd ə prəˈpoʊzl/", "提出提案", "Put forward a proposal today."),
        ("refute a claim", "/rɪˈfjuːt ə kleɪm/", "驳斥主张", "Data refute a claim easily."),
        ("acknowledge a point", "/əkˈnɑːlɪdʒ ə pɔɪnt/", "承认某点", "Acknowledge a point fairly."),
        ("concede defeat", "/kənˈsiːd dɪˈfiːt/", "承认失败", "He conceded defeat gracefully."),
        ("bear witness to", "/ber ˈwɪtnəs tə/", "见证", "Records bear witness to change."),
        ("beyond dispute", "/bɪˈjɑːnd dɪˈspjuːt/", "无可争议", "The result is beyond dispute."),
        ("open to debate", "/ˈoʊpən tə dɪˈbeɪt/", "可商榷", "The policy is open to debate."),
        ("heated debate", "/ˈhiːtɪd dɪˈbeɪt/", "激烈辩论", "A heated debate erupted."),
        ("play devil's advocate", "/pleɪ ˈdevlz ˈædvəkeɪt/", "故意唱反调", "Let me play devil's advocate."),
        ("on the one hand", "/ɑːn ðə wʌn hænd/", "一方面", "On the one hand, costs rise."),
        ("on the other hand", "/ɑːn ði ˈʌðər hænd/", "另一方面", "On the other hand, quality improves."),
        ("in my view", "/ɪn maɪ vjuː/", "在我看来", "In my view, reform is needed."),
        ("as far as I'm concerned", "/æz fɑːr æz aɪm kənˈsɜːrnd/", "就我而言", "As far as I'm concerned, it's fine."),
        ("strongly disagree", "/strɔːŋli ˌdɪsəˈɡriː/", "强烈反对", "I strongly disagree with that."),
        ("partially agree", "/ˈpɑːrʃəli əˈɡriː/", "部分同意", "I partially agree with you."),
        ("substantiate a claim", "/səbˈstænʃieɪt ə kleɪm/", "证实主张", "Substantiate a claim with data."),
        ("undermine credibility", "/ˌʌndərˈmaɪn ˌkredəˈbɪləti/", "损害可信度", "Lies undermine credibility."),
        ("distort the facts", "/dɪˈstɔːrt ðə fækts/", "歪曲事实", "Don't distort the facts."),
        ("read between the lines", "/riːd bɪˈtwiːn ðə laɪnz/", "体会言外之意", "Read between the lines carefully."),
        ("a matter of opinion", "/ə ˈmætər əv əˈpɪnjən/", "见仁见智", "Taste is a matter of opinion."),
    ]


# Continue with days 3-10 - I'll add compact but complete lists

def day3_words():
    w = [
        ("consequence", "/ˈkɑːnsɪkwens/", "n. 结果；重要性", "con- + sequ"),
        ("subsequent", "/ˈsʌbsɪkwənt/", "a. 随后的", "sub- + sequ"),
        ("attribute", "/əˈtrɪbjuːt/", "v. 归因于", "at- + tribute"),
        ("contribute", "/kənˈtrɪbjuːt/", "v. 贡献；促成", "con- + tribute"),
        ("induce", "/ɪnˈduːs/", "v. 引起", "in- + duc"),
        ("inevitable", "/ɪnˈevɪtəbl/", "a. 不可避免的", "in- + evit"),
        ("trigger", "/ˈtrɪɡər/", "v./n. 触发", "—"),
        ("undermine", "/ˌʌndərˈmaɪn/", "v. 削弱", "—"),
        ("sequence", "/ˈsiːkwəns/", "n. 顺序；序列", "sequ + -ence"),
        ("consecutive", "/kənˈsekjətɪv/", "a. 连续的", "con- + secut"),
        ("execute", "/ˈeksɪkjuːt/", "v. 执行", "ex- + secut"),
        ("prosecute", "/ˈprɑːsɪkjuːt/", "v. 起诉", "pro- + secut"),
        ("pursue", "/pərˈsuː/", "v.  pursue 追求", "pur- + sue"),
        ("ensue", "/ɪnˈsuː/", "v.  ensue  ensue", "en- + sue"),
        ("cause", "/kɔːz/", "n./v. 原因；导致", "—"),
        ("effect", "/ɪˈfekt/", "n. 效果", "ef- + fect"),
        ("affect", "/əˈfekt/", "v. 影响", "af- + fect"),
        ("impact", "/ˈɪmpækt/", "n./v. 影响", "im- + pact"),
        ("influence", "/ˈɪnfluəns/", "n./v. 影响", "in- + flu"),
        ("result", "/rɪˈzʌlt/", "n./v. 结果", "re- + sult"),
        ("outcome", "/ˈaʊtkʌm/", "n.  outcome 结果", "out + come"),
        ("correlation", "/ˌkɔːrəˈleɪʃn/", "n.  correlation 相关", "cor- + rel"),
        ("causation", "/kɔːˈzeɪʃn/", "n.  causation 因果关系", "cause"),
        ("premise", "/ˈpremɪs/", "n. 前提", "—"),
        ("therefore", "/ˈðerfɔːr/", "adv. 因此", "there + for"),
        ("hence", "/hens/", "adv.  hence 因此", "—"),
        ("thus", "/ðʌs/", "adv.  thus  thus", "—"),
        ("accordingly", "/əˈkɔːrdɪŋli/", "adv.  accordingly", "accord"),
        ("consequently", "/ˈkɑːnsɪkwently/", "adv. 因此", "consequence"),
        ("nevertheless", "/ˌnevərðəˈles/", "adv. 尽管如此", "—"),
        ("whereas", "/ˌwerˈæz/", "conj. 然而", "—"),
        ("whereby", "/werˈbaɪ/", "adv.  whereby 据此", "—"),
        ("wherein", "/werˈɪn/", "adv.  wherein 其中", "—"),
        ("provided that", "/prəˈvaɪdɪd ðæt/", "conj. 倘若", "—"),
        ("assuming that", "/əˈsuːmɪŋ ðæt/", "conj. 假设", "—"),
        ("given that", "/ˈɡɪvn ðæt/", "conj. 鉴于", "—"),
        ("stem from", "/stem frəm/", "v.  stem from 源于", "—"),
        ("derive from", "/dɪˈraɪv frəm/", "v.  derive 源于", "de- + riv"),
        ("originate", "/əˈrɪdʒɪneɪt/", "v.  originate 起源于", "origin"),
        ("generate", "/ˈdʒenəreɪt/", "v. 产生", "gen 生"),
        ("produce", "/prəˈduːs/", "v.  produce 产生", "pro- + duc"),
        ("yield", "/jiːld/", "v.  yield  yield", "—"),
        ("facilitate", "/fəˈsɪlɪteɪt/", "v.  facilitate 促进", "facil 易"),
        ("hinder", "/ˈhɪndər/", "v.  hinder 阻碍", "—"),
        ("impede", "/ɪmˈpiːd/", "v.  impede 阻碍", "im- + ped"),
        ("obstruct", "/əbˈstrʌkt/", "v.  obstruct  obstruct", "ob- + struct"),
        ("prevent", "/prɪˈvent/", "v.  prevent  prevent", "pre- + vent"),
        ("enable", "/ɪˈneɪbl/", "v.  enable  enable", "en- + able"),
        ("prompt", "/prɑːmpt/", "v.  prompt  prompt", "—"),
        ("provoke", "/prəˈvoʊk/", "v.  provoke  provoke", "pro- + voc"),
        ("stimulate", "/ˈstɪmjuleɪt/", "v.  stimulate  stimulate", "—"),
        ("exacerbate", "/ɪɡˈzæsərbeɪt/", "v.  exacerbate  exacerbate", "—"),
        ("alleviate", "/əˈliːvieɪt/", "v.  alleviate  alleviate", "—"),
        ("mitigate", "/ˈmɪtɪɡeɪt/", "v.  mitigate  mitigate", "—"),
        ("amplify", "/ˈæmplɪfaɪ/", "v.  amplify  amplify", "ampl 大"),
        ("diminish", "/dɪˈmɪnɪʃ/", "v.  diminish  diminish", "mini 小"),
        ("accumulate", "/əˈkjuːmjuleɪt/", "v.  accumulate  accumulate", "ad- + cumul"),
        ("cascade", "/kæˈskeɪd/", "n./v.  cascade  cascade", "—"),
        ("chain reaction", "/tʃeɪn riˈækʃn/", "n.  chain reaction  chain reaction", "—"),
        ("feedback", "/ˈfiːdbæk/", "n.  feedback  feedback", "—"),
        ("loop", "/luːp/", "n.  loop  loop", "—"),
        ("mechanism", "/ˈmekənɪzəm/", "n.  mechanism  mechanism", "—"),
        ("pattern", "/ˈpætərn/", "n.  pattern  pattern", "—"),
        ("trend", "/trend/", "n.  trend  trend", "—"),
        ("cycle", "/ˈsaɪkl/", "n.  cycle  cycle", "cycl 圆"),
        ("phase", "/feɪz/", "n.  phase  phase", "—"),
        ("stage", "/steɪdʒ/", "n.  stage  stage", "—"),
        ("process", "/ˈprɑːses/", "n.  process  process", "pro- + cess"),
        ("procedure", "/prəˈsiːdʒər/", "n.  procedure  procedure", "pro- + ced"),
        ("methodology", "/ˌmeθəˈdɑːlədʒi/", "n.  methodology  methodology", "method"),
        ("framework", "/ˈfreɪmwɜːrk/", "n.  framework  framework", "—"),
        ("criteria", "/kraɪˈtɪriə/", "n.  criteria  criteria", "criterion 复"),
        ("variable", "/ˈveriəbl/", "n.  variable  variable", "vari 变"),
        ("factor", "/ˈfæktər/", "n.  factor  factor", "fact 做"),
        ("determinant", "/dɪˈtɜːrmɪnənt/", "n.  determinant  determinant", "determine"),
        ("dependency", "/dɪˈpendənsi/", "n.  dependency  dependency", "depend"),
        ("interdependence", "/ˌɪntərdɪˈpendəns/", "n.  interdependence  interdependence", "inter- + depend"),
        ("causal", "/ˈkɔːzl/", "a.  causal  causal", "cause"),
        ("logical", "/ˈlɑːdʒɪkl/", "a.  logical  logical", "logic"),
        ("systematic", "/ˌsɪstəˈmætɪk/", "a.  systematic  systematic", "system"),
        ("sequential", "/sɪˈkwenʃl/", "a.  sequential  sequential", "sequence"),
        ("simultaneous", "/ˌsaɪmlˈteɪniəs/", "a.  simultaneous  simultaneous", "simul 同"),
    ]
    return w[:80]


def day3_phrases():
    return [
        ("as a consequence", "/æz ə ˈkɑːnsɪkwens/", "因此", "As a consequence, sales fell."),
        ("attribute A to B", "/əˈtrɪbjuːt eɪ tə biː/", "把 A 归因于 B", "Attribute success to luck."),
        ("contribute to", "/kənˈtrɪbjuːt tə/", "促成", "Stress contributes to illness."),
        ("trigger a debate", "/ˈtrɪɡər ə dɪˈbeɪt/", "引发争论", "It triggered a debate."),
        ("in sequence", "/ɪn ˈsiːkwəns/", "按顺序", "Events occurred in sequence."),
        ("as a result", "/æz ə rɪˈzʌlt/", "结果", "As a result, prices rose."),
        ("lead to", "/liːd tə/", "导致", "Pollution leads to disease."),
        ("result in", "/rɪˈzʌlt ɪn/", "导致", "Errors result in losses."),
        ("result from", "/rɪˈzʌlt frəm/", "源于", "Success results from effort."),
        ("stem from", "/stem frəm/", "源于", "Problems stem from neglect."),
        ("give rise to", "/ɡɪv raɪz tə/", "引起", "Changes give rise to conflict."),
        ("bring about", "/brɪŋ əˈbaʊt/", "带来", "Reform brings about growth."),
        ("account for", "/əˈkaʊnt fɔːr/", "解释；占", "Weather accounts for delays."),
        ("be attributable to", "/bi əˈtrɪbjətəbl tə/", "可归因于", "Failure is attributable to bias."),
        ("have an impact on", "/hæv ən ˈɪmpækt ɑːn/", "对…有影响", "Policy has an impact on jobs."),
        ("exert influence on", "/ɪɡˈzɜːrt ˈɪnfluəns ɑːn/", "施加影响", "Media exert influence on voters."),
        ("in turn", "/ɪn tɜːrn/", "反过来", "Costs rise and, in turn, demand falls."),
        ("by contrast", "/baɪ ˈkɑːntræst/", "相比之下", "By contrast, exports grew."),
        ("on the grounds that", "/ɑːn ðə ɡraʊndz ðæt/", "理由是", "Rejected on the grounds that it lacked proof."),
        ("for this reason", "/fɔːr ðɪs ˈriːzn/", "为此", "For this reason, we paused."),
        ("it follows that", "/ɪt ˈfɑːloʊz ðæt/", "由此可得", "It follows that costs rise."),
        ("given the circumstances", "/ˈɡɪvn ðə ˈsɜːrkəmstænsɪz/", "鉴于情况", "Given the circumstances, wait."),
        ("under the condition that", "/ˈʌndər ðə kənˈdɪʃn ðæt/", "在…条件下", "Approved under the condition that costs fall."),
        ("prevent sb from doing", "/prɪˈvent ˈsʌmbədi frəm ˈduːɪŋ/", "阻止某人做", "Rules prevent firms from cheating."),
        ("enable sb to do", "/ɪˈneɪbl ˈsʌmbədi tə duː/", "使某人能够", "Tech enables us to collaborate."),
        ("facilitate communication", "/fəˈsɪlɪteɪt kəˌmjuːnɪˈkeɪʃn/", "促进沟通", "Tools facilitate communication."),
        ("hinder progress", "/ˈhɪndər ˈprɑːɡres/", "阻碍进展", "Bureaucracy hinders progress."),
        ("impede development", "/ɪmˈpiːd dɪˈveləpmənt/", "阻碍发展", "Sanctions impede development."),
        ("exacerbate the problem", "/ɪɡˈzæsərbeɪt ðə ˈprɑːbləm/", "加剧问题", "Cuts exacerbate the problem."),
        ("alleviate suffering", "/əˈliːvieɪt ˈsʌfərɪŋ/", "减轻痛苦", "Aid alleviates suffering."),
        ("mitigate risk", "/ˈmɪtɪɡeɪt rɪsk/", "降低风险", "Diversification mitigates risk."),
        ("a chain of events", "/ə tʃeɪn əv ɪˈvents/", "一连串事件", "A chain of events unfolded."),
        ("feedback loop", "/ˈfiːdbæk luːp/", "反馈循环", "A feedback loop formed."),
        ("cause and effect", "/kɔːz ənd ɪˈfekt/", "因果关系", "Study cause and effect."),
        ("correlation does not imply causation", "/ˌkɔːrəˈleɪʃn dʌz nɑːt ɪmˈplaɪ kɔːˈzeɪʃn/", "相关不等于因果", "Remember: correlation does not imply causation."),
        ("in the first place", "/ɪn ðə fɜːrst pleɪs/", "首先；起初", "Why did it fail in the first place?"),
        ("in the long run", "/ɪn ðə lɔːŋ rʌn/", "从长远看", "In the long run, quality wins."),
        ("in the short term", "/ɪn ðə ʃɔːrt tɜːrm/", "短期来看", "In the short term, costs rise."),
        ("step by step", "/step baɪ step/", "逐步地", "Solve it step by step."),
        ("follow a procedure", "/ˈfɑːloʊ ə prəˈsiːdʒər/", "遵循程序", "Follow a procedure strictly."),
    ]


if __name__ == "__main__":
    print("Day1 words:", len(day1_words()), "phrases:", len(day1_phrases()))
    print("Day2 words:", len(day2_words()), "phrases:", len(day2_phrases()))
    print("Day3 words:", len(day3_words()), "phrases:", len(day3_phrases()))
