#!/usr/bin/env python3
"""Add 30 typed sentences to each day; keep existing words/phrases."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
BANK = ROOT / "bank"
BYDAY = ROOT / "by-day"
INDEX = ROOT / "daily-vocab-30day.md"
README = ROOT / "README.md"

TYPES = [
    "陈述句",
    "否定句",
    "一般疑问句",
    "特殊疑问句",
    "选择疑问句",
    "反意疑问句",
    "祈使句",
    "感叹句",
    "存在句",
    "被动语态",
    "现在完成时",
    "过去完成时",
    "将来时态",
    "真实条件句",
    "虚拟语气",
    "定语从句",
    "宾语从句",
    "原因状语从句",
    "让步状语从句",
    "目的状语从句",
    "比较结构",
    "强调句",
    "倒装句",
    "分词结构",
    "不定式结构",
    "动名词结构",
    "with 复合结构",
    "同位语从句",
    "插入评注",
    "形式主语 It",
]


def S(en: str, zh: str) -> tuple[str, str]:
    return (en, zh)


# Each day: exactly 30 (en, zh) in TYPES order
DAY: dict[int, list[tuple[str, str]]] = {}

DAY[1] = [
    S("Students acquire cognitive skills through deliberate practice.", "学生通过刻意练习获得认知技能。"),
    S("Many learners do not retain information without spaced review.", "许多学习者若不间隔复习就记不住信息。"),
    S("Can you comprehend the main idea of this passage?", "你能理解这段文字的大意吗？"),
    S("Why do people perceive the same event differently?", "为什么人们对同一事件的感知不同？"),
    S("Is insight the result of analysis or sudden recognition?", "洞察是分析的结果还是突然的认出？"),
    S("You recognized the pattern, didn't you?", "你认出了这个模式，对吧？"),
    S("Assimilate new concepts before moving to the next chapter.", "先吸收新概念，再进入下一章。"),
    S("What a remarkable capacity for lifelong learning!", "多么惊人的终身学习能力啊！"),
    S("There is growing interest in cognitive science education.", "人们对认知科学教育的兴趣日益增长。"),
    S("Critical thinking is taught systematically in many universities.", "批判性思维在许多大学被系统教授。"),
    S("She has already developed strong literacy skills.", "她已经培养了很强的读写能力。"),
    S("He had studied the theory before testing the hypothesis.", "他在检验假设之前就已经研究过该理论。"),
    S("We will investigate how memory consolidates during sleep.", "我们将研究睡眠如何巩固记忆。"),
    S("If you review regularly, you will retain more vocabulary.", "如果你定期复习，就会记住更多词汇。"),
    S("If I were more attentive, I would grasp abstract ideas faster.", "如果我更专注，就能更快抓住抽象概念。"),
    S("The professor who enlightened us emphasized empirical evidence.", "那位启发我们的教授强调实证证据。"),
    S("Researchers claim that practice reinforces learning.", "研究者声称练习能强化学习。"),
    S("Because concentration fades quickly, short sessions work better.", "因为专注力消退很快，短时学习更有效。"),
    S("Although the curriculum is demanding, students stay focused.", "尽管课程要求高，学生仍保持专注。"),
    S("Take notes carefully so that you can recall key insights later.", "认真记笔记，以便之后能回忆关键洞见。"),
    S("Analytical thinking is more trainable than many people assume.", "分析思维比许多人以为的更可训练。"),
    S("It is deliberate practice that builds true proficiency.", "正是刻意练习造就真正的熟练。"),
    S("Only after repeated failure did she master the subject.", "直到反复失败之后，她才精通该学科。"),
    S("Observing carefully, the team drew a valid inference.", "仔细观察后，团队作出了有效推断。"),
    S("To expand one's horizons, one must explore unfamiliar fields.", "要开阔眼界，必须探索陌生领域。"),
    S("Learning by rote rarely leads to deep comprehension.", "死记硬背很少带来深刻理解。"),
    S("With new evidence available, the hypothesis needs revision.", "有了新证据，该假设需要修订。"),
    S("The idea that cognition shapes behavior is widely accepted.", "认知塑造行为这一观点被广泛接受。"),
    S("Hands-on learning, in my view, outperforms passive listening.", "在我看来，体验式学习优于被动听讲。"),
    S("It is essential to pay attention to subtle conceptual differences.", "注意细微的概念差异至关重要。"),
]

DAY[2] = [
    S("A valid argument must rest on objective evidence.", "站得住脚的论点必须基于客观证据。"),
    S("He did not justify his claim with reliable data.", "他没有用可靠数据为自己的主张辩护。"),
    S("Do you contend that the conclusion is premature?", "你是否主张该结论为时过早？"),
    S("What perspective shapes your evaluation of the policy?", "何种视角塑造了你对该政策的评价？"),
    S("Should we assert our position or remain cautious?", "我们应断言立场还是保持谨慎？"),
    S("The evidence contradicts the rumor, doesn't it?", "证据与谣言矛盾，不是吗？"),
    S("Speculate carefully before you publish the critique.", "发表批评前请谨慎推测。"),
    S("How convincing this line of reasoning is!", "这一推理多么有说服力！"),
    S("There are several competing interpretations of the text.", "对该文本存在若干相互竞争的解释。"),
    S("The hypothesis was challenged by subsequent studies.", "该假设受到后续研究的挑战。"),
    S("Scholars have long debated the validity of this method.", "学者们长期争论该方法的有效性。"),
    S("She had already outlined her thesis before the seminar.", "研讨会前她已列出论文提纲。"),
    S("We will examine whether the claim can withstand scrutiny.", "我们将检验该主张能否经得起审视。"),
    S("If the premises are false, the conclusion collapses.", "如果前提为假，结论就会崩塌。"),
    S("If the data were clearer, we would not speculate so freely.", "如果数据更清晰，我们就不会如此随意推测。"),
    S("Critics who contradict the mainstream offer alternative views.", "反驳主流的批评者提供了替代观点。"),
    S("I believe that an objective stance reduces bias.", "我认为客观立场能减少偏见。"),
    S("Because the argument lacks evidence, it remains unpersuasive.", "因为该论点缺乏证据，所以仍缺乏说服力。"),
    S("Although he asserted his innocence, doubts persisted.", "尽管他断言自己无辜，疑虑依然存在。"),
    S("Clarify definitions so that debate stays productive.", "澄清定义，以便辩论保持建设性。"),
    S("A justified claim is stronger than a mere opinion.", "有依据的主张强于单纯意见。"),
    S("It is the evidence that validates the argument.", "正是证据使论点成立。"),
    S("Never before have we seen such polarized perspectives.", "我们从未见过如此两极分化的观点。"),
    S("Confronted with counterexamples, he revised his position.", "面对反例，他修正了立场。"),
    S("To justify a policy, one must weigh costs and benefits.", "要为政策辩护，必须权衡成本与收益。"),
    S("Speculating without data undermines scholarly credibility.", "没有数据地推测会损害学术可信度。"),
    S("With conflicting reports circulating, caution is warranted.", "在相互矛盾的报道流传时，谨慎是必要的。"),
    S("The claim that markets are always efficient is disputed.", "市场总是有效这一主张存在争议。"),
    S("Objectivity, frankly, is harder than it sounds.", "坦白说，客观性比听起来更难。"),
    S("It is necessary to distinguish assertion from proof.", "有必要区分断言与证明。"),
]

DAY[3] = [
    S("Rising costs contribute to inflationary pressure.", "成本上升促成通胀压力。"),
    S("The delay did not trigger an immediate crisis.", "延误并未立即引发危机。"),
    S("Does stress contribute to chronic illness?", "压力是否促成慢性病？"),
    S("What consequence followed the policy change?", "政策变化带来了什么后果？"),
    S("Was the failure induced by error or by design?", "失败是由失误引起还是有意为之？"),
    S("The outcome was inevitable, wasn't it?", "结果不可避免，对吧？"),
    S("Attribute success to preparation, not luck alone.", "把成功归因于准备，而非仅靠运气。"),
    S("What a chain of unexpected consequences!", "多么一连串出人意料的后果！"),
    S("There are multiple causes behind the shortage.", "短缺背后存在多重原因。"),
    S("The reform was undermined by weak enforcement.", "改革因执行不力而被削弱。"),
    S("Experts have linked the decline to demographic shifts.", "专家已将下滑与人口结构变化联系起来。"),
    S("Officials had warned of risks before the collapse.", "崩溃之前官员已警告过风险。"),
    S("Further investigation will reveal the root cause.", "进一步调查将揭示根本原因。"),
    S("If demand surges, prices will rise accordingly.", "如果需求激增，价格将相应上涨。"),
    S("If precautions had been taken, losses would have been smaller.", "若早采取预防，损失本会更小。"),
    S("Policies that induce investment can accelerate growth.", "诱发投资的政策能加速增长。"),
    S("Analysts argue that the deficit stems from overspending.", "分析人士认为赤字源于过度支出。"),
    S("Because incentives were misaligned, efficiency fell.", "因为激励错位，效率下降。"),
    S("Although the trigger seemed minor, the impact was huge.", "尽管诱因看似微小，影响却巨大。"),
    S("Diversify early so that one shock cannot ruin the plan.", "尽早多元化，以免一次冲击毁掉计划。"),
    S("Subsequent effects were more severe than initial estimates.", "后续影响比最初估计更严重。"),
    S("It is poor coordination that exacerbates the problem.", "正是协调不力加剧了问题。"),
    S("Only then did the team realize the causal chain.", "直到那时团队才意识到因果链条。"),
    S("Facing inevitable trade-offs, leaders chose stability.", "面对不可避免的取舍，领导选择了稳定。"),
    S("To prevent recurrence, address underlying causes.", "为防复发，应解决深层原因。"),
    S("Blaming individuals rarely solves systemic problems.", "指责个人很少能解决系统性问题。"),
    S("With feedback loops ignored, small errors snowballed.", "忽视反馈回路后，小错误滚成雪球。"),
    S("The fact that correlation is not causation matters.", "相关不等于因果这一事实很重要。"),
    S("In turn, higher costs reduced household consumption.", "反过来，更高成本降低了家庭消费。"),
    S("It is crucial to distinguish cause from coincidence.", "区分原因与巧合至关重要。"),
]

DAY[4] = [
    S("Independent panels evaluate public projects against clear criteria.", "独立小组依据明确标准评估公共项目。"),
    S("The board did not compensate workers for the sudden layoff.", "董事会没有对突然裁员的工人作出补偿。"),
    S("Can we assess the long-term impact with current data?", "我们能否用现有数据评估长期影响？"),
    S("Which benchmark should guide next year's performance review?", "哪项基准应指导明年的绩效评估？"),
    S("Is quality more crucial than speed in this assessment?", "在此次评估中质量是否比速度更关键？"),
    S("The difference is significant, isn't it?", "差异很显著，对吧？"),
    S("Set priorities before you allocate scarce resources.", "在配置稀缺资源前先设定优先事项。"),
    S("What a substantial improvement in accuracy!", "准确度有多么大幅度的提升！"),
    S("There are multiple dimensions to this evaluation.", "这项评估有多个维度。"),
    S("Teacher performance is assessed through peer review.", "教师表现通过同行评议来评定。"),
    S("Researchers have measured productivity gains for years.", "研究者多年来一直测量生产率提升。"),
    S("Managers had underestimated costs before the audit.", "审计前管理者低估了成本。"),
    S("The agency will raise the threshold next quarter.", "该机构将在下季度提高门槛。"),
    S("If the sample is biased, the rating will mislead.", "如果样本有偏，评分就会误导。"),
    S("If criteria were transparent, trust would increase.", "如果标准透明，信任就会增加。"),
    S("Metrics that ignore equity can distort priorities.", "忽视公平的指标会扭曲优先事项。"),
    S("Analysts argue that magnitude matters more than noise.", "分析人士认为量级比噪声更重要。"),
    S("Because evidence is negligible, claims stay weak.", "因为证据可忽略，主张仍然薄弱。"),
    S("Although the advantage seems clear, risks remain.", "尽管优势看似明显，风险仍在。"),
    S("Collect better data so that assessment becomes fair.", "收集更好数据，以便评估变得公平。"),
    S("This method is more precise than last year's model.", "该方法比去年的模型更精确。"),
    S("It is validity that determines scientific credibility.", "正是有效性决定科学可信度。"),
    S("Rarely do trivial errors receive so much attention.", "琐碎错误很少受到如此多关注。"),
    S("Weighing pros and cons, the committee chose caution.", "权衡利弊后，委员会选择了谨慎。"),
    S("To compensate for gaps, provide additional training.", "为弥补差距，应提供额外培训。"),
    S("Ranking schools solely by scores can harm diversity.", "仅按分数给学校排名可能损害多样性。"),
    S("With limited funding, priority setting becomes political.", "在资金有限时，优先排序变得政治化。"),
    S("The belief that bigger always means better is flawed.", "越大越好这一信念是有缺陷的。"),
    S("In practice, adequate resources rarely arrive on time.", "实践中，充足资源很少按时到位。"),
    S("It is essential to distinguish value from price.", "区分价值与价格至关重要。"),
]


DAY[5] = [
    S("Markets transform rapidly under technological pressure.", "市场在技术压力下快速转型。"),
    S("Prices did not fluctuate as wildly as predicted.", "价格并未如预测那般剧烈波动。"),
    S("Will automation accelerate job displacement this decade?", "自动化会在本十年加速就业替代吗？"),
    S("How did the industry evolve after the breakthrough?", "突破之后该行业如何演变？"),
    S("Is the shift gradual evolution or sudden disruption?", "这种转变是渐进演变还是突然颠覆？"),
    S("Momentum is building, isn't it?", "势头正在增强，对吧？"),
    S("Adapt to change before the window closes.", "在窗口关闭前适应变化。"),
    S("What a volatile year for emerging markets!", "对新兴市场来说多么动荡的一年！"),
    S("There is little stability during major transitions.", "重大转型期间几乎没有稳定。"),
    S("Outdated systems are being phased out nationwide.", "过时系统正在全国逐步淘汰。"),
    S("Startups have upgraded their platforms repeatedly.", "初创公司已多次升级其平台。"),
    S("The firm had already diversified before the recession.", "衰退前该公司已完成多元化。"),
    S("Regulators will tighten rules after the next surge.", "下一轮激增后监管将收紧规则。"),
    S("If demand soars, supply chains will stretch thin.", "如果需求飙升，供应链将吃紧。"),
    S("If reforms had arrived earlier, decline might have slowed.", "若改革更早到来，下滑本可能放缓。"),
    S("Companies that innovate constantly survive turbulence.", "不断创新的公司能在动荡中生存。"),
    S("Economists say the recovery will gain momentum soon.", "经济学家称复苏很快将积蓄势头。"),
    S("Because the market is volatile, hedging is common.", "因为市场动荡，对冲很常见。"),
    S("Although growth improved, structural problems remain.", "尽管增长改善，结构问题仍在。"),
    S("Invest early so that compound returns can accumulate.", "尽早投资，以便复利回报得以积累。"),
    S("Digital transformation is faster than traditional reform.", "数字化转型快于传统改革。"),
    S("It is innovation that drives long-term productivity.", "正是创新驱动长期生产率。"),
    S("Only after the crash did investors seek safer assets.", "崩溃之后投资者才寻求更安全资产。"),
    S("Facing setbacks, the team modified its strategy.", "面对挫折，团队修改了策略。"),
    S("To restore confidence, communicate a clear timeline.", "为恢复信心，应沟通清晰时间表。"),
    S("Delaying upgrades increases the risk of failure.", "推迟升级会增加失败风险。"),
    S("With new competitors emerging, incumbents must evolve.", "随着新竞争者出现，在位者必须演变。"),
    S("The notion that change is always progress is naive.", "认为变化总是进步的观念很幼稚。"),
    S("In the short term, transition costs can look painful.", "短期看，转型成本可能显得痛苦。"),
    S("It is difficult to predict every market fluctuation.", "预测每一次市场波动都很困难。"),
]

DAY[6] = [
    S("Coastal cities remain vulnerable to extreme weather.", "沿海城市仍易受极端天气影响。"),
    S("The agency did not mitigate the hazard in time.", "该机构未能及时缓解危害。"),
    S("Can resilience be built before the next crisis?", "能否在下一场危机前建立韧性？"),
    S("What obstacles prevent effective emergency response?", "哪些障碍妨碍有效应急响应？"),
    S("Is the threat natural, human-made, or both?", "威胁是自然的、人为的，还是两者皆有？"),
    S("The system is fragile, isn't it?", "系统很脆弱，对吧？"),
    S("Take precautions before entering hazardous zones.", "进入危险区域前请采取预防措施。"),
    S("What a catastrophic failure of risk management!", "多么灾难性的风险管理失败！"),
    S("There are early warning signs before most collapses.", "大多数崩溃前都有预警信号。"),
    S("Critical infrastructure must be safeguarded continuously.", "关键基础设施必须持续得到保障。"),
    S("Communities have faced repeated floods this decade.", "本十年社区已多次遭遇洪水。"),
    S("Officials had underestimated the scale of the disaster.", "官员曾低估灾害规模。"),
    S("New protocols will address bottlenecks in supply.", "新规程将解决供应瓶颈。"),
    S("If tensions escalate, markets will panic quickly.", "如果紧张加剧，市场将迅速恐慌。"),
    S("If safeguards were stronger, casualties would decrease.", "若保障更强，伤亡会减少。"),
    S("Policies that exacerbate inequality deepen social risk.", "加剧不平等的政策会加深社会风险。"),
    S("Experts warn that complacency invites future crises.", "专家警告自满会招致未来危机。"),
    S("Because loopholes remain, fraud continues to spread.", "因为漏洞仍在，欺诈继续蔓延。"),
    S("Although the conflict eased, underlying friction persists.", "尽管冲突缓和，深层摩擦仍在。"),
    S("Train responders so that emergencies do not turn chaotic.", "培训应急人员，以免紧急情况陷入混乱。"),
    S("Prevention is cheaper than post-disaster recovery.", "预防比灾后恢复更便宜。"),
    S("It is weak governance that amplifies every shock.", "正是薄弱治理放大每一次冲击。"),
    S("Nowhere is vulnerability more visible than in slums.", "脆弱性在贫民窟最为可见。"),
    S("Confronting the problem early, leaders limited damage.", "及早正视问题，领导层限制了损害。"),
    S("To tackle root causes, fund long-term resilience.", "要解决根源，应为长期韧性提供资金。"),
    S("Ignoring warnings often leads to irreversible harm.", "忽视警告常导致不可逆伤害。"),
    S("With limited hospitals, casualties rose sharply.", "医院有限时，伤亡急剧上升。"),
    S("The fear that panic itself worsens outcomes is real.", "恐慌本身会恶化结果的担忧是真实的。"),
    S("In crisis, coordinated action outweighs isolated heroism.", "危机中，协调行动胜过孤立英雄主义。"),
    S("It is urgent to remove obstacles to aid delivery.", "清除援助运送障碍十分紧迫。"),
]

DAY[7] = [
    S("Regular review helps learners retain crucial concepts.", "定期复习帮助学习者记住关键概念。"),
    S("The report did not justify the optimistic forecast.", "报告未能证明乐观预测的合理性。"),
    S("Have you evaluated the inevitable trade-offs yet?", "你评估过那些不可避免的取舍了吗？"),
    S("Which consequence concerns you most after the reform?", "改革后哪种后果最令你担忧？"),
    S("Should we transform the system or merely adjust it?", "我们应改造系统还是仅作调整？"),
    S("The argument is still valid, isn't it?", "该论点仍然成立，对吧？"),
    S("Acquire evidence before you assert a strong claim.", "在断言强硬主张前先获取证据。"),
    S("How complex this chain of causes and effects is!", "这条因果链条多么复杂！"),
    S("There are useful overlaps among this week's word families.", "本周词族之间有有用的交叉。"),
    S("Risks are mitigated when teams share timely information.", "团队及时共享信息时，风险得以缓解。"),
    S("You have already practiced both analysis and evaluation.", "你已同时练习了分析与评估。"),
    S("She had consolidated memory before the final exam.", "期末考前她已巩固记忆。"),
    S("Tomorrow we will revisit crisis vocabulary under pressure.", "明天我们将在压力下重温危机词汇。"),
    S("If you contradict yourself, credibility will suffer.", "如果你自相矛盾，可信度会受损。"),
    S("If criteria were clearer, assessment would feel fairer.", "如果标准更清晰，评估会更显公平。"),
    S("Learners who stay focused acquire skills faster.", "保持专注的学习者获得技能更快。"),
    S("Teachers believe that insight follows structured struggle.", "教师认为洞察来自有结构的挣扎。"),
    S("Because fluctuation is normal, panic is rarely helpful.", "因为波动正常，恐慌很少有帮助。"),
    S("Although the crisis passed, vulnerability remains.", "尽管危机已过，脆弱性仍在。"),
    S("Review word roots so that recall becomes automatic.", "复习词根，以便回忆变得自动。"),
    S("A justified claim is stronger than speculation alone.", "有依据的主张强于单纯推测。"),
    S("It is consistent practice that turns knowledge into skill.", "正是持续练习把知识变成技能。"),
    S("Not until week two did many students notice the pattern.", "直到第二周许多学生才注意到规律。"),
    S("Combining themes, we can see deeper connections.", "结合主题，我们能看到更深联系。"),
    S("To undermine a myth, present empirical counterevidence.", "要削弱迷思，应提出实证反证。"),
    S("Memorizing lists without sentences limits real mastery.", "只背清单不练句子会限制真正掌握。"),
    S("With mixed review, forgotten items resurface usefully.", "通过混合复习，遗忘项会有益地重现。"),
    S("The principle that evidence beats assertion still holds.", "证据胜过断言这一原则仍然成立。"),
    S("Overall, this checkpoint measures both breadth and depth.", "总体而言，这一检查点兼顾广度与深度。"),
    S("It is wise to mark weak items for tonight's review.", "今晚复习标出薄弱项是明智的。"),
]

DAY[8] = [
    S("Civil rights expansions reshape democratic institutions.", "公民权利扩展重塑民主体制。"),
    S("The law did not integrate marginalized communities fairly.", "法律未能公平地融入边缘社群。"),
    S("Does transparency strengthen public accountability?", "透明度是否增强公共问责？"),
    S("Who holds legitimate authority in this dispute?", "这场争议中谁拥有合法权威？"),
    S("Should welfare prioritize efficiency or equity?", "福利应优先效率还是公平？"),
    S("Discrimination remains widespread, doesn't it?", "歧视仍然普遍，对吧？"),
    S("Empower citizens through accessible civic education.", "通过可及的公民教育赋权公民。"),
    S("What an inspiring grassroots movement this has become!", "这场基层运动变得多么鼓舞人心！"),
    S("There is growing solidarity across urban neighborhoods.", "城市社区间的团结在增强。"),
    S("Corrupt officials were prosecuted under new legislation.", "腐败官员依据新立法被起诉。"),
    S("Voters have demanded judicial reform for years.", "选民多年来要求司法改革。"),
    S("Activists had petitioned before the protest began.", "抗议开始前活动人士已请愿。"),
    S("Parliament will debate immigration policy next month.", "议会下月将辩论移民政策。"),
    S("If inequality widens, social cohesion will erode.", "如果不平等扩大，社会凝聚将削弱。"),
    S("If voting were simpler, turnout would likely rise.", "若投票更简便，投票率可能上升。"),
    S("Institutions that exclude minorities lose legitimacy.", "排斥少数群体的制度会失去合法性。"),
    S("Many citizens believe bureaucracy delays justice.", "许多公民认为官僚制拖延正义。"),
    S("Because privilege is invisible, reform meets resistance.", "因为特权不易察觉，改革遭遇阻力。"),
    S("Although democracy expanded, civic duty declined.", "尽管民主扩展，公民义务却下降。"),
    S("Publish open data so that watchdog groups can audit.", "公开数据，以便监督团体审计。"),
    S("Inclusive policies are more durable than coercive ones.", "包容政策比强制政策更持久。"),
    S("It is equal opportunity that underpins social mobility.", "正是机会均等支撑社会流动。"),
    S("Nowhere is civic neglect more costly than in education.", "公民忽视在教育领域代价最高。"),
    S("Facing injustice, volunteers organized legal aid.", "面对不公，志愿者组织了法律援助。"),
    S("To protect privacy, regulate surveillance carefully.", "为保护隐私，应谨慎监管监控。"),
    S("Stereotyping groups undermines democratic deliberation.", "刻板印象群体会损害民主审议。"),
    S("With weak rule of law, corruption thrives easily.", "法治薄弱时，腐败容易滋生。"),
    S("The principle that all citizens are equal remains contested in practice.", "公民一律平等这一原则在实践中仍有争议。"),
    S("In short, institutions matter more than slogans.", "简言之，制度比口号更重要。"),
    S("It is difficult to rebuild trust after systemic abuse.", "系统性滥用之后重建信任十分困难。"),
]

DAY[9] = [
    S("Fiscal policy can stimulate a weak economy.", "财政政策可刺激疲弱经济。"),
    S("The surplus did not offset the mounting public debt.", "盈余未能抵消不断攀升的公共债务。"),
    S("Will higher interest rates curb inflation effectively?", "更高利率能否有效抑制通胀？"),
    S("How should governments allocate scarce resources?", "政府应如何配置稀缺资源？"),
    S("Is recession a cyclical dip or a structural break?", "衰退是周期性回落还是结构性断裂？"),
    S("Productivity growth remains sluggish, doesn't it?", "生产率增长仍然乏力，对吧？"),
    S("Diversify investments before the bubble bursts.", "在泡沫破裂前分散投资。"),
    S("What a dramatic collapse in commodity prices!", "大宗商品价格多么剧烈的崩盘！"),
    S("There is little liquidity in distressed markets.", "困境市场中几乎没有流动性。"),
    S("Tariffs were imposed to protect domestic industries.", "征收关税以保护国内产业。"),
    S("Central banks have tightened monetary policy sharply.", "央行已大幅收紧货币政策。"),
    S("Investors had fled risk assets before the crash.", "崩盘前投资者已逃离风险资产。"),
    S("Subsidies will target renewable energy next year.", "明年补贴将瞄准可再生能源。"),
    S("If wages stagnate, consumption will weaken further.", "如果工资停滞，消费将进一步走弱。"),
    S("If debt were sustainable, panic would be unnecessary.", "若债务可持续，恐慌本无必要。"),
    S("Firms that raise productivity can absorb higher costs.", "提高生产率的企业能消化更高成本。"),
    S("Markets expect that unemployment will edge upward.", "市场预期失业率将小幅上升。"),
    S("Because credit tightened, small businesses struggled.", "因为信贷收紧，小企业陷入困境。"),
    S("Although exports recovered, the deficit persisted.", "尽管出口复苏，逆差仍在。"),
    S("Build reserves so that shocks do not force austerity.", "建立储备，以免冲击迫使紧缩。"),
    S("Capital investment is riskier than cash holdings.", "资本投资比持有现金风险更高。"),
    S("It is consumer spending that drives short-term growth.", "正是消费支出驱动短期增长。"),
    S("Seldom do stimulus packages please every faction.", "刺激计划很少让各方都满意。"),
    S("Facing insolvency, the bank sought emergency funding.", "面对无力偿付，银行寻求紧急资金。"),
    S("To restore solvency, cut nonessential expenditure.", "为恢复偿付能力，削减非必要开支。"),
    S("Speculating on leverage can amplify losses rapidly.", "杠杆投机会迅速放大亏损。"),
    S("With inflation elevated, real incomes decline.", "通胀高企时，实际收入下降。"),
    S("The claim that markets self-correct instantly is contested.", "市场瞬间自我纠正这一主张存在争议。"),
    S("On balance, gradual tightening reduces volatility.", "总体而言，渐进收紧可降低波动。"),
    S("It is hard to forecast commodity price swings precisely.", "精确预测大宗商品价格波动很难。"),
]

DAY[10] = [
    S("Cutting-edge algorithms reshape digital platforms.", "尖端算法重塑数字平台。"),
    S("Legacy systems did not become obsolete overnight.", "遗留系统并非一夜之间过时。"),
    S("Can automation replace complex engineering judgment?", "自动化能否取代复杂工程判断？"),
    S("What cybersecurity threats worry regulators most?", "哪些网络安全威胁最令监管担忧？"),
    S("Is the prototype ready for deployment or still experimental?", "原型是已可部署还是仍在实验？"),
    S("Patents encourage innovation, don't they?", "专利鼓励创新，对吧？"),
    S("Encrypt sensitive data before you transmit it.", "传输前先加密敏感数据。"),
    S("What a sophisticated semiconductor supply chain!", "多么精密的半导体供应链！"),
    S("There is intense competition in cloud computing.", "云计算领域竞争激烈。"),
    S("User interfaces are optimized for faster interaction.", "用户界面被优化以加快交互。"),
    S("Labs have simulated climate scenarios for decades.", "实验室数十年来一直模拟气候情景。"),
    S("The startup had patented the method before fundraising.", "融资前初创公司已为该方法申请专利。"),
    S("The company will deploy machine learning next quarter.", "公司下季度将部署机器学习。"),
    S("If bandwidth expands, latency will fall noticeably.", "如果带宽扩大，延迟将明显下降。"),
    S("If standards were open, compatibility would improve.", "若标准开放，兼容性会改善。"),
    S("Tools that digitize archives preserve cultural memory.", "数字化档案的工具保存文化记忆。"),
    S("Engineers believe robotics will transform manufacturing.", "工程师认为机器人将改造制造业。"),
    S("Because malware spreads quickly, updates matter.", "因为恶意软件传播快，更新很重要。"),
    S("Although AI is powerful, surveillance risks rise.", "尽管 AI 强大，监控风险上升。"),
    S("Debug carefully so that critical failures are avoided.", "仔细调试，以避免关键故障。"),
    S("State-of-the-art chips are costlier than older models.", "最先进芯片比旧型号更昂贵。"),
    S("It is scalable design that enables rapid growth.", "正是可扩展设计使快速增长成为可能。"),
    S("Only after the breach did executives fund cybersecurity.", "入侵之后高管才为网络安全拨款。"),
    S("Facing obsolescence, firms renovated their stacks.", "面对过时，公司翻新了技术栈。"),
    S("To implement an algorithm, validate edge cases.", "要实现算法，应验证边界情况。"),
    S("Ignoring privacy erodes trust in digital services.", "忽视隐私会侵蚀对数字服务的信任。"),
    S("With sensors everywhere, data volumes explode.", "传感器无处不在时，数据量爆炸。"),
    S("The hope that technology alone solves inequality is naive.", "仅靠技术解决不平等的希望很幼稚。"),
    S("In practice, human-computer interaction still frustrates users.", "实践中，人机交互仍令用户沮丧。"),
    S("It is vital to protect intellectual property carefully.", "仔细保护知识产权至关重要。"),
]

DAY[11] = [
    S("Sustainable development requires protecting biodiversity.", "可持续发展需要保护生物多样性。"),
    S("Factories did not stop contaminating local rivers.", "工厂并未停止污染当地河流。"),
    S("Can conservation policies reverse ecosystem collapse?", "保护政策能否扭转生态系统崩溃？"),
    S("Where do the largest carbon emissions originate?", "最大碳排放源自何处？"),
    S("Is degradation reversible or already permanent?", "退化是可逆的还是已成永久？"),
    S("The habitat is fragile, isn't it?", "栖息地很脆弱，对吧？"),
    S("Reduce emissions before tipping points are crossed.", "在越过临界点前减少排放。"),
    S("What an alarming decline in marine biodiversity!", "海洋生物多样性下降多么惊人！"),
    S("There is still hope for ecological recovery.", "生态恢复仍有希望。"),
    S("Wetlands are being restored across the region.", "该地区湿地正在得到修复。"),
    S("Scientists have tracked deforestation for decades.", "科学家数十年来追踪森林砍伐。"),
    S("The city had ignored pollution warnings for years.", "该市多年来忽视污染警告。"),
    S("New standards will limit industrial discharge soon.", "新标准不久将限制工业排放。"),
    S("If temperatures rise further, droughts will intensify.", "如果气温继续上升，干旱将加剧。"),
    S("If plastics were banned sooner, oceans would be cleaner.", "若塑料更早被禁，海洋本会更干净。"),
    S("Communities that conserve forests secure water supplies.", "保护森林的社区能保障供水。"),
    S("Ecologists argue that biodiversity buffers climate shocks.", "生态学家认为生物多样性可缓冲气候冲击。"),
    S("Because habitats fragment, species migrate or vanish.", "因为栖息地碎片化，物种迁移或消失。"),
    S("Although renewable energy expanded, coal persisted.", "尽管可再生能源扩展，煤炭仍在。"),
    S("Plant native species so that ecosystems can recover.", "种植本地物种，以便生态系统恢复。"),
    S("Clean air is more valuable than short-term profits.", "清洁空气比短期利润更有价值。"),
    S("It is overconsumption that drives resource depletion.", "正是过度消费驱动资源耗竭。"),
    S("Nowhere are emissions harder to cut than in heavy industry.", "重工业减排难度最大。"),
    S("Facing scarcity, planners invested in conservation.", "面对稀缺，规划者投资于保护。"),
    S("To protect biodiversity, expand marine reserves.", "为保护生物多样性，应扩大海洋保护区。"),
    S("Contaminating groundwater endangers public health.", "污染地下水危及公共卫生。"),
    S("With rising seas, coastal ecology changes rapidly.", "海平面上升时，海岸生态快速变化。"),
    S("The claim that growth need not harm nature is debated.", "增长不必伤害自然这一主张存在争论。"),
    S("Ultimately, stewardship decides environmental outcomes.", "最终，管理责任决定环境结果。"),
    S("It is urgent to cut carbon emissions this decade.", "本十年削减碳排放十分紧迫。"),
]

DAY[12] = [
    S("Empathy motivates prosocial behavior in groups.", "共情激发群体中的亲社会行为。"),
    S("Stereotypes did not disappear after the campaign.", "刻板印象并未在运动后消失。"),
    S("Does anxiety impair working memory under pressure?", "焦虑是否在压力下损害工作记忆？"),
    S("What incentives shape adolescent risk-taking?", "哪些激励塑造青少年冒险行为？"),
    S("Is prejudice explicit bias or implicit association?", "偏见是显性偏见还是内隐联想？"),
    S("Impulse control matters, doesn't it?", "冲动控制很重要，对吧？"),
    S("Challenge stereotypes before they harden into norms.", "在刻板印象固化为规范前挑战它们。"),
    S("How powerful peer pressure can become!", "同辈压力可以变得多么强大！"),
    S("There is rising concern about student anxiety.", "对学生焦虑的担忧在上升。"),
    S("Motivation is often strengthened by timely feedback.", "动机常因及时反馈而增强。"),
    S("Psychologists have studied empathy across cultures.", "心理学家跨文化研究共情。"),
    S("The child had internalized the stereotype early.", "孩子很早就内化了刻板印象。"),
    S("Schools will introduce mindfulness programs next term.", "学校下学期将引入正念项目。"),
    S("If incentives align, cooperation will increase.", "如果激励一致，合作将增加。"),
    S("If stigma were reduced, more people would seek help.", "若污名减少，更多人会求助。"),
    S("People who show empathy resolve conflicts faster.", "表现共情的人解决冲突更快。"),
    S("Therapists believe that talking reduces anxiety.", "治疗师认为倾诉能减轻焦虑。"),
    S("Because impulses arise quickly, pause techniques help.", "因为冲动来得快，暂停技巧有帮助。"),
    S("Although prejudice declined publicly, bias persisted privately.", "尽管公开偏见下降，私下偏见仍在。"),
    S("Design incentives so that healthy habits stick.", "设计激励，以便健康习惯得以保持。"),
    S("Intrinsic motivation lasts longer than external rewards.", "内在动机比外部奖励更持久。"),
    S("It is early intervention that prevents chronic anxiety.", "正是早期干预防止慢性焦虑。"),
    S("Rarely do stereotypes match individual reality.", "刻板印象很少符合个体现实。"),
    S("Facing rejection, she rebuilt self-efficacy gradually.", "面对拒绝，她逐渐重建自我效能。"),
    S("To reduce prejudice, expand intergroup contact.", "为减少偏见，应扩大群际接触。"),
    S("Labeling people can reinforce harmful stereotypes.", "给人贴标签会强化有害刻板印象。"),
    S("With social support present, resilience improves.", "有社会支持时，韧性提升。"),
    S("The idea that personality never changes is outdated.", "性格永不改变这一想法已经过时。"),
    S("In therapy, honesty matters more than perfection.", "在治疗中，诚实比完美更重要。"),
    S("It is healthy to acknowledge emotional vulnerability.", "承认情绪脆弱是健康的。"),
]

DAY[13] = [
    S("Mass media transmit narratives across borders quickly.", "大众传媒迅速跨境传递叙事。"),
    S("The headline did not distort the core facts badly.", "标题并未严重歪曲核心事实。"),
    S("Can audiences detect media bias without training?", "受众未经训练能否察觉媒体偏见？"),
    S("Why do false stories circulate faster than corrections?", "为何假新闻比更正传播更快？"),
    S("Is the source anonymous whistleblowing or mere rumor?", "消息源是匿名吹哨还是纯属谣言？"),
    S("Authenticity still matters online, doesn't it?", "网络上真实性仍然重要，对吧？"),
    S("Fact-check claims before you share the clip.", "分享片段前先核查事实。"),
    S("What a sensational piece of clickbait this is!", "这条标题党内容多么耸动！"),
    S("There is intense competition for audience engagement.", "争夺受众互动十分激烈。"),
    S("Documentaries are often funded by nonprofit foundations.", "纪录片常由非营利基金会资助。"),
    S("Journalists have exposed corruption through investigations.", "记者通过调查揭露腐败。"),
    S("Editors had cut the segment before broadcast.", "播出前编辑已删减该片段。"),
    S("Platforms will label AI-generated content soon.", "平台很快将标注 AI 生成内容。"),
    S("If algorithms amplify outrage, polarization will deepen.", "如果算法放大愤怒，极化将加深。"),
    S("If citations were required, plagiarism would decline.", "若要求引用，剽窃会减少。"),
    S("Outlets that distort truth lose long-term trust.", "歪曲真相的媒体失去长期信任。"),
    S("Readers know that headlines oversimplify complex issues.", "读者知道标题会简化复杂问题。"),
    S("Because echo chambers form, opposing views vanish.", "因为回音室形成，对立观点消失。"),
    S("Although press freedom expanded, threats persist.", "尽管新闻自由扩展，威胁仍在。"),
    S("Paraphrase carefully so that meaning remains accurate.", "仔细释义，以便意义保持准确。"),
    S("Investigative reporting is costlier than wire summaries.", "调查报道比电讯摘要成本更高。"),
    S("It is media literacy that protects public discourse.", "正是媒介素养保护公共话语。"),
    S("Never before has misinformation scaled so quickly.", "虚假信息从未如此快速规模化。"),
    S("Facing lawsuits, the paper issued a correction.", "面对诉讼，该报发布更正。"),
    S("To combat disinformation, fund independent fact-checkers.", "为打击虚假信息，资助独立事实核查。"),
    S("Quoting out of context damages democratic debate.", "断章取义损害民主辩论。"),
    S("With virality rewarded, nuance disappears fast.", "病毒传播受奖励时，细微差别迅速消失。"),
    S("The claim that platforms are neutral is contested.", "平台中立这一主张存在争议。"),
    S("Ironically, more channels have not meant better truth.", "讽刺的是，更多渠道并未带来更好真相。"),
    S("It is important to verify sources before publishing.", "发表前核实来源很重要。"),
]

DAY[14] = [
    S("Integrated policies link society, economy, and ecology.", "综合政策把社会、经济与生态联系起来。"),
    S("Innovation alone did not solve media bias overnight.", "单靠创新并未一夜消除媒体偏见。"),
    S("Can sustainable growth motivate civic participation?", "可持续增长能否激励公民参与？"),
    S("Which theme from this week still feels hardest?", "本周哪个主题仍觉得最难？"),
    S("Is the bottleneck technology, regulation, or psychology?", "瓶颈是技术、监管还是心理？"),
    S("These word families overlap usefully, don't they?", "这些词族有用交叉，对吧？"),
    S("Review ecology terms before the mixed self-test.", "混合自测前先复习生态术语。"),
    S("What a dense week of interdisciplinary vocabulary!", "多么密集的一周跨学科词汇！"),
    S("There are clear patterns across Days 8–13.", "第8–13天之间有清晰规律。"),
    S("Social incentives are shaped by media narratives.", "社会激励由媒体叙事塑造。"),
    S("You have already connected economy with sustainability.", "你已把经济与可持续联系起来。"),
    S("She had mastered tech terms before the psychology set.", "在心理学词集前她已掌握科技术语。"),
    S("We will recycle weak items in tonight's drill.", "今晚训练将重练薄弱项。"),
    S("If you integrate themes, recall becomes richer.", "如果你整合主题，回忆会更丰富。"),
    S("If bias were easier to spot, media literacy would soar.", "若偏见更易识别，媒介素养会飙升。"),
    S("Learners who revisit roots remember derivatives longer.", "重温词根的学习者更久记得派生词。"),
    S("Teachers note that mixed review beats massed cramming.", "教师指出混合复习胜过集中死记。"),
    S("Because topics diverge, deliberate linking helps.", "因为话题发散，有意联结有帮助。"),
    S("Although the load is heavy, spaced practice works.", "尽管负荷重，间隔练习有效。"),
    S("Sort cards by theme so that retrieval stays flexible.", "按主题分类卡片，以便提取保持灵活。"),
    S("Civic vocabulary is denser than everyday chat.", "公民词汇比日常闲聊更密。"),
    S("It is cumulative exposure that builds fluent access.", "正是累积接触建立流利提取。"),
    S("Not until the review day did gaps become obvious.", "直到复习日缺口才变得明显。"),
    S("Combining examples, we see shared argument patterns.", "结合例子，我们看到共享论证模式。"),
    S("To stay motivated, track small weekly wins.", "为保持动机，追踪每周小胜利。"),
    S("Skipping sentence practice weakens productive skills.", "跳过句子练习会削弱产出技能。"),
    S("With six themes mixed, interference is expected.", "六主题混合时，干扰在所难免。"),
    S("The rule that roots unlock families still applies.", "词根打开词族这一规则仍然适用。"),
    S("Overall, this checkpoint rewards breadth plus precision.", "总体而言，本检查点奖励广度加精确。"),
    S("It is useful to rewrite hard phrases in your own words.", "用自己的话改写难短语很有用。"),
]

DAY[15] = [
    S("Good papers propose solutions supported by evidence.", "好论文提出有证据支撑的方案。"),
    S("The draft did not cite primary sources adequately.", "草稿未充分引用一手来源。"),
    S("Can you paraphrase the thesis without distortion?", "你能否在不歪曲的情况下改写论点？"),
    S("What methodology produced these findings?", "何种方法产生了这些发现？"),
    S("Is this an implication or an explicit claim?", "这是隐含意义还是明确主张？"),
    S("The conclusion follows, doesn't it?", "结论由此得出，对吧？"),
    S("Illustrate abstract claims with concrete examples.", "用具体例子说明抽象主张。"),
    S("How elegant this logical structure appears!", "这一逻辑结构显得多么优雅！"),
    S("There is little discussion of counterarguments here.", "此处几乎没有讨论反驳论点。"),
    S("Key terms are defined in the introduction.", "关键术语在引言中被界定。"),
    S("Scholars have revised the framework repeatedly.", "学者多次修订该框架。"),
    S("She had outlined the literature before drafting.", "起草前她已列出文献综述提纲。"),
    S("We will submit the manuscript after peer review.", "同行评议后我们将提交手稿。"),
    S("If evidence is thin, the claim will not persuade.", "如果证据薄弱，主张无法说服人。"),
    S("If citations were accurate, plagiarism risks would fall.", "若引用准确，剽窃风险会下降。"),
    S("Authors who imply too much leave readers confused.", "暗示过多的作者让读者困惑。"),
    S("Reviewers believe that clarity beats jargon.", "审稿人认为清晰胜过行话。"),
    S("Because the method is opaque, replication fails.", "因为方法不透明，复制失败。"),
    S("Although the abstract is concise, details matter.", "尽管摘要简洁，细节仍重要。"),
    S("Define variables so that measurement stays consistent.", "界定变量，以便测量保持一致。"),
    S("A well-founded claim is stronger than speculation.", "有根据的主张强于推测。"),
    S("It is the thesis statement that anchors the essay.", "正是中心论点句锚定全文。"),
    S("Only after revision did the argument cohere.", "修订之后论证才连贯。"),
    S("Comparing studies, we highlight methodological gaps.", "比较研究后，我们突出方法缺口。"),
    S("To conclude persuasively, restate limited scope.", "要有说服力地收尾，应重述有限范围。"),
    S("Avoiding plagiarism protects academic integrity.", "避免剽窃保护学术诚信。"),
    S("With better examples, implications become clearer.", "有更好例子时，含义更清晰。"),
    S("The assumption that readers share background is risky.", "假定读者有共同背景是危险的。"),
    S("In academic writing, precision outweighs flourish.", "学术写作中，精确胜过辞藻。"),
    S("It is necessary to distinguish summary from critique.", "有必要区分摘要与评论。"),
]

DAY[16] = [
    S("The two models stand in sharp contrast.", "两种模型形成鲜明对比。"),
    S("The results did not reverse earlier findings.", "结果并未推翻先前发现。"),
    S("Does diversity strengthen or fragment consensus?", "多样性是强化还是碎片化共识？"),
    S("Where does your view differ from your counterpart's?", "你的观点与对等方何处不同？"),
    S("Is the paradox real or merely rhetorical?", "悖论是真实的还是纯修辞？"),
    S("The wording is ambiguous, isn't it?", "措辞模棱两可，对吧？"),
    S("State alternatives clearly before choosing one.", "选择前先把替代方案说清楚。"),
    S("What a striking similarity between the cases!", "案例之间多么惊人的相似！"),
    S("There are nonetheless important exceptions.", "尽管如此仍有重要例外。"),
    S("Opposite conclusions were drawn from the same data.", "同一数据得出了相反结论。"),
    S("Debates have diversified across disciplines.", "辩论已跨学科多样化。"),
    S("They had preferred plan A before new evidence arrived.", "新证据到来前他们更倾向方案A。"),
    S("We will compare frameworks in the next section.", "下一节我们将比较框架。"),
    S("If assumptions differ, conclusions will diverge.", "如果假设不同，结论将分叉。"),
    S("If definitions were shared, disputes would shrink.", "若定义共享，争议会缩小。"),
    S("Claims that ignore nuance invite misunderstanding.", "忽视细微差别的主张易引发误解。"),
    S("Critics argue that conversely trends are overstated.", "批评者认为相反趋势被夸大。"),
    S("Because contexts differ, analogies can mislead.", "因为语境不同，类比可能误导。"),
    S("Although costs rose, quality improved nonetheless.", "尽管成本上升，质量仍改善。"),
    S("Clarify contrasts so that readers track the logic.", "澄清对比，以便读者跟上逻辑。"),
    S("Plan A is riskier than its counterpart abroad.", "方案A比国外对等方案风险更高。"),
    S("It is ambiguity that fuels endless dispute.", "正是含糊助长无尽争议。"),
    S("Not only is the gap large, it is widening.", "差距不但大，而且还在扩大。"),
    S("Differing on methods, the teams still shared goals.", "虽方法不同，团队仍共享目标。"),
    S("To resolve the paradox, separate levels of analysis.", "要解决悖论，应区分分析层次。"),
    S("Preferring simplicity can erase meaningful diversity.", "偏好简单可能抹去有意义的多样性。"),
    S("With conflicting metrics, rankings become unstable.", "指标冲突时，排名变得不稳定。"),
    S("The notion that opposites never coexist is false.", "对立永不共存这一观念是错误的。"),
    S("By comparison, the second model is more flexible.", "相比较，第二模型更灵活。"),
    S("It is useful to mark subtle distinctions explicitly.", "明确标出细微区别很有用。"),
]

DAY[17] = [
    S("A large proportion of samples showed dense clustering.", "很大一部分样本呈现密集聚类。"),
    S("The minority did not reach the required threshold.", "少数派未达到所需门槛。"),
    S("Can approximate figures mislead policy decisions?", "约数是否会误导政策决定？"),
    S("What magnitude of change counts as significant?", "多大变化才算显著？"),
    S("Is the distribution sparse or heavily concentrated?", "分布是稀疏还是高度集中？"),
    S("The majority supports the measure, doesn't it?", "多数支持该措施，对吧？"),
    S("Maximize accuracy before you minimize cost.", "在最小化成本前先最大化准确度。"),
    S("What an enormous volume of statistical noise!", "多么巨大的统计噪声量！"),
    S("There is only a handful of reliable benchmarks.", "可靠基准只有少数几个。"),
    S("Survey results are weighted by population density.", "调查结果按人口密度加权。"),
    S("Researchers have expanded sample sizes repeatedly.", "研究者多次扩大样本量。"),
    S("They had calculated the median before the mean.", "他们在均值之前先算了中位数。"),
    S("The bureau will publish new statistics next week.", "该局下周将公布新统计。"),
    S("If the ratio rises, inequality will widen.", "如果比率上升，不平等将扩大。"),
    S("If measurement were precise, debates would cool.", "若测量精确，争论会降温。"),
    S("Models that ignore scale produce false confidence.", "忽视规模的模型产生虚假信心。"),
    S("Demographers say prevalence varies by region.", "人口学家称流行率因地区而异。"),
    S("Because the margin of error is large, caution is due.", "因为误差幅度大，需要谨慎。"),
    S("Although averages look stable, extremes matter.", "尽管均值看似稳定，极端值仍重要。"),
    S("Increase the sample so that estimates tighten.", "增大样本，以便估计更紧。"),
    S("Vast datasets are messier than tidy textbook examples.", "海量数据比教科书干净例子更乱。"),
    S("It is proportion, not raw totals, that clarifies risk.", "澄清风险的是比例而非原始总数。"),
    S("Seldom is infinite growth available in finite systems.", "有限系统中很少有无限增长。"),
    S("Facing scarce data, analysts used approximate bounds.", "面对稀缺数据，分析师使用近似边界。"),
    S("To compare magnitudes, convert units carefully.", "要比较量级，应仔细换算单位。"),
    S("Counting without context can distort public debate.", "没有语境的计数会扭曲公共辩论。"),
    S("With denser sampling, rare events become visible.", "抽样更密时，罕见事件变得可见。"),
    S("The assumption that bigger samples always help is incomplete.", "更大样本总有帮助这一假设不完整。"),
    S("On average, incremental gains compound over time.", "平均而言，增量收益随时间复利。"),
    S("It is easy to confuse frequency with importance.", "很容易把频率与重要性混淆。"),
]

DAY[18] = [
    S("Temporary measures can bridge imminent shortfalls.", "临时措施可以填补迫在眉睫的缺口。"),
    S("The deadline did not postpone automatically.", "截止日期并未自动推迟。"),
    S("Will the milestone arrive ahead of schedule?", "里程碑会提前到来吗？"),
    S("How long is the duration of the pilot phase?", "试点阶段持续多久？"),
    S("Is the condition chronic or merely seasonal?", "病情是慢性还是仅季节性？"),
    S("The meeting is overdue, isn't it?", "会议已逾期，对吧？"),
    S("Synchronize calendars before you set the agenda.", "设定议程前先同步日历。"),
    S("What a punctual delivery under tight timelines!", "在紧张时间线下多么准时的交付！"),
    S("There is little interval between successive deadlines.", "连续截止日期之间几乎没有间隔。"),
    S("The launch was preceded by months of testing.", "发布前进行了数月测试。"),
    S("Teams have endured repeated schedule slips.", "团队已忍受多次进度延误。"),
    S("Managers had deferred hiring before the freeze.", "冻结前管理者已推迟招聘。"),
    S("The board will review the timetable tomorrow.", "董事会明天将审阅时间表。"),
    S("If delays continue, costs will escalate.", "如果延误持续，成本将上升。"),
    S("If warnings had been timely, damage would be less.", "若警告及时，损害本会更小。"),
    S("Projects that miss milestones lose investor trust.", "错过里程碑的项目失去投资者信任。"),
    S("Planners believe the recovery will be gradual.", "规划者认为复苏将是渐进的。"),
    S("Because the risk is imminent, action cannot wait.", "因为风险迫近，行动不能等待。"),
    S("Although the phase ended, monitoring continues.", "尽管阶段结束，监测仍继续。"),
    S("Extend the window so that quality does not suffer.", "延长窗口，以免质量受损。"),
    S("Ongoing work is slower than a one-off sprint.", "持续性工作比一次性冲刺更慢。"),
    S("It is punctuality that keeps complex schedules viable.", "正是准时使复杂日程可行。"),
    S("Only after the audit did the delay become visible.", "审计之后延误才变得可见。"),
    S("Facing an abrupt shift, staff adapted procedures.", "面对突然转变，员工调整了流程。"),
    S("To meet the deadline, cut nonessential features.", "为赶上截止日期，削减非必要功能。"),
    S("Prolonging conflict exhausts public patience.", "延长冲突耗尽公众耐心。"),
    S("With overlapping sessions, fatigue accumulates.", "会期重叠时，疲劳累积。"),
    S("The idea that faster always equals better is simplistic.", "更快总等于更好这一想法过于简单。"),
    S("Meanwhile, preliminary results guide next steps.", "与此同时，初步结果指导下一步。"),
    S("It is hard to endure uncertainty without a timeline.", "没有时间线很难忍受不确定性。"),
]

DAY[19] = [
    S("Proficient teams accomplish complex goals efficiently.", "熟练团队高效完成复杂目标。"),
    S("The intern was not yet capable of solo decisions.", "实习生尚不能独立决策。"),
    S("Can training facilitate rapid skill transfer?", "培训能否促进技能快速迁移？"),
    S("What expertise distinguishes top performers?", "何种专长区分顶尖表现者？"),
    S("Is potential innate talent or cultivated capacity?", "潜力是先天天赋还是培养出的能力？"),
    S("Performance improved markedly, didn't it?", "表现明显改善，对吧？"),
    S("Practice deliberately before you claim mastery.", "在宣称精通前先刻意练习。"),
    S("What outstanding achievement under tight constraints!", "在紧张约束下多么杰出的成就！"),
    S("There is room for improvement in every skill set.", "每一套技能都有改进空间。"),
    S("Competence is demonstrated through real tasks.", "能力通过真实任务得到证明。"),
    S("Athletes have strengthened capacity all season.", "运动员整季都在增强能力。"),
    S("She had qualified for the exam before coaching began.", "辅导开始前她已取得考试资格。"),
    S("The lab will enhance productivity with new tools.", "实验室将用新工具提升生产率。"),
    S("If feedback is timely, learning will accelerate.", "如果反馈及时，学习将加速。"),
    S("If barriers were removed, more talent would excel.", "若障碍清除，更多人才会脱颖而出。"),
    S("Leaders who empower staff unlock hidden potential.", "赋能员工的领导释放隐藏潜力。"),
    S("Coaches believe fluent practice beats passive study.", "教练认为流利练习胜过被动学习。"),
    S("Because incentives misalign, effective effort drops.", "因为激励错位，有效努力下降。"),
    S("Although credentials help, performance decides.", "尽管资历有帮助，表现才作决定。"),
    S("Train consistently so that proficiency becomes durable.", "持续训练，以便熟练变得持久。"),
    S("Efficient methods save more time than longer hours.", "高效方法比更长工时更省时间。"),
    S("It is deliberate practice that creates excellence.", "正是刻意练习造就卓越。"),
    S("Seldom do amateurs outperform trained specialists overnight.", "业余者很少一夜超越训练有素的专家。"),
    S("Facing failure, he rebuilt confidence gradually.", "面对失败，他逐渐重建信心。"),
    S("To accomplish more, eliminate low-value tasks.", "要完成更多，剔除低价值任务。"),
    S("Underperforming quietly still harms team outcomes.", "默默表现不佳仍损害团队结果。"),
    S("With better scaffolding, novices become capable faster.", "有更好支架时，新手更快变得能干。"),
    S("The myth that talent needs no practice is harmful.", "天赋无需练习这一迷思有害。"),
    S("In competitions, peak performance is rare and fragile.", "竞赛中，巅峰表现稀少且脆弱。"),
    S("It is possible to cultivate expertise at any age.", "任何年龄都可能培养专长。"),
]

DAY[20] = [
    S("Ethical standards protect dignity in research.", "伦理标准在研究中保护尊严。"),
    S("The firm did not comply with privacy regulations.", "该公司未遵守隐私规章。"),
    S("Does informed consent always prevent harm?", "知情同意是否总能防止伤害？"),
    S("Where should accountability begin in a hierarchy?", "问责应在等级制何处开始？"),
    S("Is the act unlawful, unethical, or both?", "该行为是非法、不道德，还是两者皆是？"),
    S("Integrity still matters in politics, doesn't it?", "政治中正直仍然重要，对吧？"),
    S("Rectify mistakes before trust erodes further.", "在信任进一步侵蚀前纠正错误。"),
    S("What a serious breach of professional ethics!", "多么严重的职业伦理违反！"),
    S("There is growing demand for corporate transparency.", "对企业透明的需求在增长。"),
    S("Whistleblowers are protected under new guidelines.", "吹哨人受新指南保护。"),
    S("Courts have upheld equal rights repeatedly.", "法院多次维护平等权利。"),
    S("The board had ignored conflicts of interest earlier.", "董事会早前忽视了利益冲突。"),
    S("Auditors will examine compliance next quarter.", "审计员下季度将检查合规。"),
    S("If norms collapse, cooperation becomes fragile.", "如果规范崩溃，合作变得脆弱。"),
    S("If penalties were certain, misconduct would decline.", "若处罚确定，不当行为会减少。"),
    S("Codes that lack enforcement invite cynicism.", "缺乏执行的准则招致犬儒。"),
    S("Citizens believe fairness requires due process.", "公民认为公平需要正当程序。"),
    S("Because stigma persists, victims stay silent.", "因为污名持续，受害者保持沉默。"),
    S("Although laws exist, unlawful practices continue.", "尽管法律存在，非法做法仍继续。"),
    S("Publish protocols so that review boards can decide.", "公布规程，以便审查委员会裁决。"),
    S("Moral obligation can outweigh short-term profit.", "道德义务可以压过短期利润。"),
    S("It is transparency that deters corrupt practice.", "正是透明度威慑腐败行为。"),
    S("Nowhere is ethical failure more costly than in medicine.", "医学中伦理失败代价最高。"),
    S("Facing a dilemma, she chose the harder honesty.", "面对困境，她选择了更难的诚实。"),
    S("To uphold justice, separate power from privilege.", "为维护正义，应将权力与特权分离。"),
    S("Abusing authority destroys institutional legitimacy.", "滥用权威摧毁制度合法性。"),
    S("With clear guidelines, compliance becomes easier.", "有清晰指南时，合规更容易。"),
    S("The principle that consent must be informed is fundamental.", "同意必须知情这一原则是根本的。"),
    S("In governance, stewardship beats extractive control.", "治理中，管理责任胜过榨取式控制。"),
    S("It is wrong to treat people merely as means.", "把人仅当作手段是错误的。"),
]

DAY[21] = [
    S("Clear methodology helps authors conclude carefully.", "清晰方法帮助作者谨慎得出结论。"),
    S("The contrast did not eliminate every ambiguity.", "对比并未消除所有含糊。"),
    S("Have you verified the temporary threshold yet?", "你核实过临时门槛了吗？"),
    S("Which ethical criterion guides your evaluation?", "哪项伦理标准指导你的评估？"),
    S("Is the quantity estimate approximate or exact?", "数量估计是近似还是精确？"),
    S("Potential still needs practice, doesn't it?", "潜力仍需练习，对吧？"),
    S("Propose alternatives before you oppose the plan.", "反对计划前先提出替代方案。"),
    S("How tightly these academic themes interconnect!", "这些学术主题联系多么紧密！"),
    S("There are recurring patterns across Days 15–20.", "第15–20天有反复出现的模式。"),
    S("Evidence is cited to support each major claim.", "引用证据支撑每个主要主张。"),
    S("You have already practiced concession and purpose clauses.", "你已练习过让步与目的从句。"),
    S("She had compared proportions before drawing inferences.", "作推断前她已比较比例。"),
    S("We will mix ethics vocabulary into writing drills.", "我们将把伦理词汇混入写作训练。"),
    S("If deadlines slip, conclusions will be rushed.", "如果截止日期延误，结论会仓促。"),
    S("If norms were clearer, compliance would improve.", "若规范更清晰，合规会改善。"),
    S("Writers who quantify claims invite sharper critique.", "量化主张的作者招致更尖锐批评。"),
    S("Editors insist that feasible plans beat vague hopes.", "编辑坚持可行计划胜过模糊希望。"),
    S("Because time is limited, prioritize high-yield review.", "因为时间有限，优先高收益复习。"),
    S("Although volume is large, depth still matters.", "尽管体量大，深度仍重要。"),
    S("Schedule intervals so that retention stays strong.", "安排间隔，以便保持力保持强劲。"),
    S("Ethical clarity is rarer than technical fluency.", "伦理清晰比技术流利更罕见。"),
    S("It is consistent criteria that make assessment fair.", "正是一致标准使评估公平。"),
    S("Not until synthesis did the week’s logic click.", "直到综合时本周逻辑才通。"),
    S("Balancing quantity and quality, choose precision.", "平衡数量与质量时，选择精确。"),
    S("To excel, convert passive recognition into production.", "要出众，把被动识别转化为产出。"),
    S("Skipping sentence types weakens exam readiness.", "跳过句型会削弱应试准备。"),
    S("With mixed themes, deliberate retrieval is essential.", "主题混合时，有意提取至关重要。"),
    S("The rule that examples beat definitions still holds.", "例子胜过定义这一规则仍然成立。"),
    S("Overall, this review rewards flexible application.", "总体而言，本次复习奖励灵活应用。"),
    S("It is smart to log recurring grammar weaknesses tonight.", "今晚记录反复出现的语法弱点很明智。"),
]

DAY[22] = [
    S("Empirical frameworks clarify abstract concepts.", "实证框架澄清抽象概念。"),
    S("The paradigm did not shift after one study.", "范式并未因一项研究而转变。"),
    S("Can perception distort a working hypothesis?", "感知会否扭曲工作假设？"),
    S("What assumptions underlie this conceptual model?", "何种假定支撑这一概念模型？"),
    S("Is the claim theoretical speculation or tested inference?", "该主张是理论推测还是已检验推断？"),
    S("The premise seems coherent, doesn't it?", "前提看似连贯，对吧？"),
    S("Define abstract terms before building arguments.", "构建论证前先界定抽象术语。"),
    S("How profound this intellectual dilemma appears!", "这一智识困境显得多么深刻！"),
    S("There is tension between concrete cases and theory.", "具体案例与理论之间存在张力。"),
    S("Hypotheses are refined through repeated testing.", "假设通过反复检验而精炼。"),
    S("Philosophers have debated ontology for centuries.", "哲学家数世纪争论本体论。"),
    S("She had formed a conception before collecting data.", "收集数据前她已形成概念。"),
    S("The seminar will explore cognitive frameworks tomorrow.", "研讨会明天将探讨认知框架。"),
    S("If assumptions fail, the model will collapse.", "如果假定失败，模型将崩溃。"),
    S("If nuance were valued, debates would be richer.", "若重视细微差别，辩论会更丰富。"),
    S("Theories that ignore paradox invite oversimplification.", "忽视悖论的理论招致过度简化。"),
    S("Scholars argue that metaphors shape perception.", "学者认为隐喻塑造感知。"),
    S("Because abstraction hides detail, examples matter.", "因为抽象隐藏细节，例子重要。"),
    S("Although the schema helps, it can mislead.", "尽管图式有帮助，也可能误导。"),
    S("Test implications so that speculation stays grounded.", "检验含义，以便推测保持落地。"),
    S("Concrete examples teach faster than pure abstraction.", "具体例子比纯抽象教得更快。"),
    S("It is the paradigm that organizes scattered facts.", "正是范式组织零散事实。"),
    S("Seldom is a single axiom sufficient for explanation.", "单一公理很少足以解释。"),
    S("Facing contradiction, researchers revised premises.", "面对矛盾，研究者修订前提。"),
    S("To capture essence, strip away incidental noise.", "要抓住本质，剥离附带噪声。"),
    S("Misinterpreting symbols generates false certainty.", "误解符号产生虚假确定性。"),
    S("With better frameworks, inquiry becomes cumulative.", "有更好框架时，探究变得可累积。"),
    S("The belief that intuition replaces evidence is dangerous.", "直觉取代证据这一信念很危险。"),
    S("In short, rigorous concepts discipline thinking.", "简言之，严谨概念约束思维。"),
    S("It is difficult to separate perception from judgment.", "把感知与判断分开很难。"),
]

DAY[23] = [
    S("Hidden agendas influence public debate quietly.", "隐藏议程悄然影响公共辩论。"),
    S("The campaign did not persuade skeptical voters.", "运动未能说服怀疑的选民。"),
    S("Can soft power dominate without coercion?", "软实力能否在无胁迫下占据主导？"),
    S("Who steers the narrative in this controversy?", "这场争议中谁引导叙事？"),
    S("Is pressure peer influence or institutional control?", "压力是同辈影响还是制度控制？"),
    S("Manipulation remains hard to detect, doesn't it?", "操控仍难察觉，对吧？"),
    S("Resist intimidation before norms collapse.", "在规范崩溃前抵制恐吓。"),
    S("How subtle this rhetorical strategy seems!", "这一修辞策略显得多么微妙！"),
    S("There is unequal leverage across stakeholders.", "利益相关方之间杠杆不平等。"),
    S("Dissent was suppressed during the emergency.", "紧急状态期间异议被压制。"),
    S("Lobbyists have reinforced industry talking points.", "游说者强化了行业话术。"),
    S("Mediators had negotiated before talks collapsed.", "谈判破裂前调解人已进行斡旋。"),
    S("Regulators will intervene if monopolies form.", "若形成垄断，监管将介入。"),
    S("If incentives change, behavior will follow.", "如果激励改变，行为将跟随。"),
    S("If transparency were higher, abuse would decline.", "若透明度更高，滥用会减少。"),
    S("Leaders who empower citizens reduce fear.", "赋权公民的领导减少恐惧。"),
    S("Analysts warn that propaganda distorts consent.", "分析人士警告宣传扭曲同意。"),
    S("Because peer pressure is strong, defiance is costly.", "因为同辈压力强，违抗代价高。"),
    S("Although influence is soft, effects can be hard.", "尽管影响柔和，效果可以强硬。"),
    S("Set clear rules so that coercion becomes unnecessary.", "设定清晰规则，使胁迫变得不必要。"),
    S("Hard power is blunter than careful persuasion.", "硬实力比细致说服更生硬。"),
    S("It is framing that shapes what people notice.", "正是框定塑造人们注意什么。"),
    S("Only after leaks did the agenda become visible.", "泄密之后议程才变得可见。"),
    S("Facing backlash, officials moderated their stance.", "面对反弹，官员缓和了立场。"),
    S("To deter misconduct, raise the certainty of penalties.", "为威慑不当行为，提高处罚确定性。"),
    S("Exploiting vulnerability destroys long-term legitimacy.", "利用脆弱性摧毁长期合法性。"),
    S("With concentrated power, accountability weakens.", "权力集中时，问责削弱。"),
    S("The claim that markets need no governance is extreme.", "市场无需治理这一主张过于极端。"),
    S("In politics, narrative often outweighs raw data.", "政治中，叙事常压过原始数据。"),
    S("It is risky to confuse influence with truth.", "把影响与真相混淆是危险的。"),
]

DAY[24] = [
    S("Infrastructure shapes the hierarchy of opportunity.", "基础设施塑造机会的等级结构。"),
    S("The mechanism did not synthesize conflicting goals.", "该机制未能综合冲突目标。"),
    S("Can modular components stabilize complex systems?", "模块化组件能否稳定复杂系统？"),
    S("Where does this framework place accountability?", "该框架把问责置于何处？"),
    S("Is the structure centralized or loosely networked?", "结构是集中的还是松散联网的？"),
    S("The system looks robust, doesn't it?", "系统看起来稳健，对吧？"),
    S("Map components before you redesign the pipeline.", "重新设计流水线前先绘制组件。"),
    S("What an intricate institutional architecture!", "多么错综的制度架构！"),
    S("There are bottlenecks at every layer of delivery.", "交付每一层都有瓶颈。"),
    S("Standards are constructed through lengthy negotiation.", "标准通过漫长协商构建。"),
    S("Engineers have upgraded critical nodes repeatedly.", "工程师多次升级关键节点。"),
    S("Planners had modeled traffic before construction.", "施工前规划者已模拟交通。"),
    S("The ministry will publish a new systems blueprint.", "该部将公布新的系统蓝图。"),
    S("If one node fails, cascades will spread.", "如果一个节点失败，级联将扩散。"),
    S("If interfaces were standardized, synthesis would improve.", "若接口标准化，综合会改善。"),
    S("Designs that ignore hierarchy create confusion.", "忽视等级的设计造成混乱。"),
    S("Architects argue that frameworks discipline creativity.", "建筑师认为框架约束创造力。"),
    S("Because coupling is tight, local faults go global.", "因为耦合紧密，局部故障变全局。"),
    S("Although modules help, integration remains hard.", "尽管模块有帮助，集成仍难。"),
    S("Document interfaces so that teams can collaborate.", "记录接口，以便团队协作。"),
    S("Loose coupling is safer than brittle centralization.", "松耦合比脆弱集中更安全。"),
    S("It is infrastructure that enables scalable growth.", "正是基础设施使可扩展增长成为可能。"),
    S("Nowhere is complexity more visible than in logistics.", "物流中复杂性最为可见。"),
    S("Facing overload, operators isolated failing components.", "面对过载，操作员隔离了故障组件。"),
    S("To strengthen resilience, add redundant pathways.", "为增强韧性，增加冗余路径。"),
    S("Overcomplicating structures slows everyday decisions.", "结构过度复杂拖慢日常决策。"),
    S("With clearer schemas, onboarding becomes faster.", "有更清晰图式时，入职更快。"),
    S("The thesis that systems self-organize perfectly is doubtful.", "系统完美自组织这一论题可疑。"),
    S("In engineering, synthesis beats isolated brilliance.", "工程中，综合胜过孤立才华。"),
    S("It is essential to test mechanisms under stress.", "在压力下测试机制至关重要。"),
]

DAY[25] = [
    S("Advocates defend controversial reforms publicly.", "倡导者公开为有争议改革辩护。"),
    S("The panel did not reach a durable consensus.", "小组未达成持久共识。"),
    S("Can persuasion replace coercive enforcement?", "说服能否取代强制执行？"),
    S("Whose stance dominates the current dispute?", "谁的立场主导当前争议？"),
    S("Is opposition principled dissent or mere obstruction?", "反对是原则性异议还是纯粹阻挠？"),
    S("The controversy continues, doesn't it?", "争议仍在继续，对吧？"),
    S("Defend your claim with verifiable evidence.", "用可核实证据为自己的主张辩护。"),
    S("What a heated dispute over basic definitions!", "围绕基本定义的争议多么激烈！"),
    S("There is little common ground between camps.", "阵营之间几乎没有共同点。"),
    S("Compromise proposals were rejected by hardliners.", "妥协提案被强硬派拒绝。"),
    S("Negotiators have narrowed disagreements slowly.", "谈判者缓慢缩小分歧。"),
    S("Both sides had prepared talking points beforehand.", "双方事先都准备了话术要点。"),
    S("Courts will hear arguments next month.", "法院下月将听取辩论。"),
    S("If trust returns, consensus will become possible.", "如果信任回归，共识将成为可能。"),
    S("If rhetoric cooled, mediation would work better.", "若言辞降温，调解会更有效。"),
    S("Leaders who refuse dialogue prolong conflict.", "拒绝对话的领导延长冲突。"),
    S("Observers believe the stance is mainly symbolic.", "观察者认为该立场主要是象征性的。"),
    S("Because stakes are high, positions harden.", "因为利害重大，立场硬化。"),
    S("Although facts overlap, interpretations clash.", "尽管事实重叠，解释冲突。"),
    S("Clarify terms so that debate stays substantive.", "澄清术语，以便辩论保持实质。"),
    S("Constructive dissent is healthier than silent consent.", "建设性异议比沉默同意更健康。"),
    S("It is evidence that should settle factual disputes.", "应靠证据解决事实争议。"),
    S("Never has civic discourse felt more polarized.", "公民话语从未如此极化。"),
    S("Facing deadlock, mediators reframed the agenda.", "面对僵局，调解人重构议程。"),
    S("To oppose effectively, propose a feasible alternative.", "要有效反对，应提出可行替代。"),
    S("Personalizing disagreement destroys deliberation.", "把分歧个人化会摧毁审议。"),
    S("With shared facts, persuasion becomes possible.", "有共享事实时，说服成为可能。"),
    S("The dogma that one side owns truth fuels hostility.", "一方独占真相的教条助长敌意。"),
    S("Beyond dispute, process legitimacy still matters.", "无可争议的是，程序合法性仍重要。"),
    S("It is hard to persuade without listening first.", "不先倾听很难说服。"),
]

DAY[26] = [
    S("Researchers verify claims against empirical evidence.", "研究者依据实证证据核实主张。"),
    S("The correlation did not validate the causal story.", "相关并未验证因果叙事。"),
    S("Can a small sample support a strong criterion?", "小样本能否支撑强标准？"),
    S("Which variables confound the observed effect?", "哪些变量混淆了观测效应？"),
    S("Is the source primary evidence or secondary citation?", "来源是一手证据还是二手引用？"),
    S("The finding replicates, doesn't it?", "发现可复现，对吧？"),
    S("Cite original studies before generalizing widely.", "广泛概括前先引用原始研究。"),
    S("What careful selection criteria this trial used!", "这项试验用了多么仔细的选拔标准！"),
    S("There is insufficient evidence for firm conclusions.", "没有足够证据支持坚定结论。"),
    S("Data were validated through independent audits.", "数据经独立审计验证。"),
    S("Labs have refined measurement protocols over years.", "实验室多年来精炼测量规程。"),
    S("Analysts had checked outliers before modeling.", "建模前分析师已检查异常值。"),
    S("The journal will require open data next year.", "该期刊明年将要求开放数据。"),
    S("If bias enters sampling, estimates will skew.", "如果抽样出现偏差，估计将偏斜。"),
    S("If criteria were pre-registered, fishing would decline.", "若标准预注册，数据挖掘会减少。"),
    S("Studies that ignore confounders mislead policy.", "忽视混杂因素的研究误导政策。"),
    S("Statisticians warn that significance is not importance.", "统计学家警告显著性不等于重要性。"),
    S("Because noise is high, replication is essential.", "因为噪声高，复现至关重要。"),
    S("Although trends look clear, uncertainty bands remain.", "尽管趋势看似清晰，不确定区间仍在。"),
    S("Predefine outcomes so that analysis stays honest.", "预先界定结果，以便分析保持诚实。"),
    S("Verified claims travel farther than rumors eventually.", "经核实的主张最终比谣言传得更远。"),
    S("It is transparent methods that earn scientific trust.", "正是透明方法赢得科学信任。"),
    S("Only after reanalysis did errors become obvious.", "再分析之后错误才变得明显。"),
    S("Facing mixed results, the team revised hypotheses.", "面对混合结果，团队修订假设。"),
    S("To verify quickly, triangulate independent sources.", "要快速核实，应三角验证独立来源。"),
    S("Cherry-picking evidence undermines credibility.", "挑选证据会损害可信度。"),
    S("With larger samples, confidence intervals shrink.", "样本更大时，置信区间缩小。"),
    S("The myth that one study settles debate is false.", "一项研究终结辩论这一迷思是错误的。"),
    S("In research, caution complements curiosity.", "研究中，谨慎与好奇互补。"),
    S("It is crucial to report negative findings too.", "报告阴性发现也同样关键。"),
]

DAY[27] = [
    S("Comprehensive reviews make implicit assumptions explicit.", "全面综述使隐含假定变得明确。"),
    S("The plan is not yet feasible under current constraints.", "在当前约束下该计划尚不可行。"),
    S("Is the wording ambiguous or merely tentative?", "措辞是模棱两可还是仅试探性？"),
    S("Why does susceptibility to bias increase online?", "为何线上更易受偏见影响？"),
    S("Should the rule be explicit guidance or flexible norm?", "规则应是明确指南还是灵活规范？"),
    S("The outcome looks inevitable, doesn't it?", "结果看起来不可避免，对吧？"),
    S("Make criteria explicit before scoring begins.", "评分开始前先把标准说清楚。"),
    S("How ambiguous this legal clause remains!", "这一法律条款仍然多么含糊！"),
    S("There is tentative support for the alternate model.", "对替代模型有试探性支持。"),
    S("Feasible options are preferred by risk-averse boards.", "规避风险的董事会偏好可行选项。"),
    S("Editors have clarified vague adjectives repeatedly.", "编辑多次澄清模糊形容词。"),
    S("Reviewers had flagged implicit claims earlier.", "审稿人早前已标出隐含主张。"),
    S("The handbook will define key evaluative terms.", "手册将界定关键评价术语。"),
    S("If language stays ambiguous, disputes will multiply.", "如果语言保持含糊，争议将增多。"),
    S("If standards were comprehensive, gaps would shrink.", "若标准全面，缺口会缩小。"),
    S("Policies that stay tentative invite opportunistic delay.", "保持试探性的政策招致机会主义拖延。"),
    S("Lawyers argue that explicit consent reduces liability.", "律师认为明确同意降低责任。"),
    S("Because nuance is subtle, overgeneralization thrives.", "因为细微差别微妙，过度概括盛行。"),
    S("Although the threat seems inevitable, responses vary.", "尽管威胁看似不可避免，应对各异。"),
    S("Define adjectives carefully so that scoring is fair.", "仔细界定形容词，以便评分公平。"),
    S("Explicit rules are clearer than implicit customs.", "明确规则比隐含习俗更清晰。"),
    S("It is ambiguity that allows selective interpretation.", "正是含糊允许选择性解释。"),
    S("Rarely is a comprehensive fix also cheap.", "全面修复很少同时便宜。"),
    S("Facing uncertainty, managers issued tentative guidance.", "面对不确定性，管理者发布试探性指南。"),
    S("To reduce susceptibility, teach critical habits.", "为降低易感性，应教授批判习惯。"),
    S("Overusing intensifiers weakens academic tone.", "过度使用强调词削弱学术语气。"),
    S("With precise modifiers, claims become testable.", "有精确修饰语时，主张变得可检验。"),
    S("The idea that adjectives are trivial is mistaken.", "形容词无关紧要这一想法是错的。"),
    S("In exams, feasible answers beat perfect fantasies.", "考试中，可行答案胜过完美幻想。"),
    S("It is useful to pair each adjective with a clear example.", "给每个形容词配一个清晰例子很有用。"),
]

DAY[28] = [
    S("A coherent framework links concepts to evidence.", "连贯框架把概念与证据联系起来。"),
    S("Influence alone did not settle the structural dispute.", "单靠影响并未解决结构性争议。"),
    S("Have you verified the ambiguous criterion yet?", "你核实过那个含糊标准了吗？"),
    S("Which paradigm best explains this mechanism?", "哪种范式最能解释该机制？"),
    S("Is consensus authentic agreement or suppressed dissent?", "共识是真实同意还是被压制的异议？"),
    S("The evidence looks empirical, doesn't it?", "证据看似实证，对吧？"),
    S("Map structures before you debate abstract claims.", "辩论抽象主张前先绘制结构。"),
    S("How tightly Days 22–27 lock together!", "第22–27天联系多么紧密！"),
    S("There are recurring logic patterns across hard themes.", "难主题间有反复出现的逻辑模式。"),
    S("Assumptions are challenged through careful critique.", "假定通过仔细批评受到挑战。"),
    S("You have already practiced inversion and cleft sentences.", "你已练习倒装与强调句。"),
    S("She had reviewed influence vocabulary before structures.", "结构词之前她已复习影响词汇。"),
    S("We will recycle weak adjectives in mixed drills.", "混合训练将重练薄弱形容词。"),
    S("If frameworks conflict, choose transparent criteria.", "如果框架冲突，选择透明标准。"),
    S("If persuasion were evidence-based, trust would rise.", "若说服基于证据，信任会上升。"),
    S("Learners who synthesize themes write stronger essays.", "综合主题的学习者写出更强作文。"),
    S("Tutors note that hard weeks reward persistence.", "辅导指出艰难周奖励坚持。"),
    S("Because abstraction is dense, examples unlock meaning.", "因为抽象密集，例子解锁意义。"),
    S("Although volume is high, selective deep work wins.", "尽管体量大，选择性深度学习获胜。"),
    S("Cluster roots so that recall stays organized.", "聚类词根，以便回忆保持有序。"),
    S("Empirical claims travel farther than vague rhetoric.", "实证主张比含糊修辞传得更远。"),
    S("It is synthesis that turns lists into understanding.", "正是综合把清单变成理解。"),
    S("Not until this review did contradictions surface.", "直到本次复习矛盾才浮现。"),
    S("Combining cases, we test whether mechanisms hold.", "结合案例，我们检验机制是否成立。"),
    S("To consolidate, produce original sentences tonight.", "为巩固，今晚产出原创句子。"),
    S("Avoiding controversy vocabulary limits debate skills.", "回避争议词汇限制辩论技能。"),
    S("With mixed retrieval, interference becomes training.", "混合提取时，干扰变成训练。"),
    S("The principle that clarity beats cleverness still applies.", "清晰胜过聪明这一原则仍然适用。"),
    S("Overall, advanced weeks demand slower, deeper passes.", "总体而言，高阶周需要更慢更深的过关。"),
    S("It is wise to mark any sentence type you still mix up.", "标出你仍混淆的句型是明智的。"),
]

DAY[29] = [
    S("Policymakers take fiscal costs into account carefully.", "决策者仔细把财政成本考虑在内。"),
    S("The reform did not pave the way for equal access.", "改革并未为平等准入铺路。"),
    S("Does growth at the expense of health make sense?", "以健康为代价的增长说得通吗？"),
    S("To what extent should privacy constrain platforms?", "隐私应在多大程度上约束平台？"),
    S("Is the rise cyclical recovery or structural shift?", "上升是周期性复苏还是结构转变？"),
    S("The figures are consistent with forecasts, aren't they?", "数据与预测一致，对吧？"),
    S("Attach importance to process as well as outcomes.", "既重视结果也重视过程。"),
    S("What lasting impact this modest change may give rise to!", "这一细微变化可能引发多么持久的影响！"),
    S("There is much left to be desired in enforcement.", "执行方面仍远不尽人意。"),
    S("Long-run gains are often discounted by markets.", "长期收益常被市场贴现。"),
    S("Scholars have shed light on hidden trade-offs.", "学者阐明了隐藏取舍。"),
    S("Ministers had regarded the issue as secondary earlier.", "部长们早前将该问题视为次要。"),
    S("The committee will revisit the expense rules soon.", "委员会很快将重审费用规则。"),
    S("If incentives align, compliance will become consistent.", "如果激励一致，合规将变得一致。"),
    S("If costs were shared fairly, resistance would fall.", "若成本公平分摊，阻力会下降。"),
    S("Policies that ignore extent of harm invite backlash.", "忽视伤害程度的政策招致反弹。"),
    S("Analysts believe the rise is bound to slow.", "分析人士认为上升注定放缓。"),
    S("Because data conflict, regard claims with caution.", "因为数据冲突，应谨慎看待主张。"),
    S("Although growth continued, welfare left much to be desired.", "尽管增长继续，福利仍远不尽人意。"),
    S("Clarify scope so that evaluation stays consistent.", "澄清范围，以便评估保持一致。"),
    S("In the long run, credibility outweighs quick wins.", "从长远看，可信度胜过速胜。"),
    S("It is transparency that paves the way for trust.", "正是透明为信任铺路。"),
    S("Only with open books can expense abuse be checked.", "只有账目公开才能遏制费用滥用。"),
    S("Facing trade-offs, the board attached priority to safety.", "面对取舍，董事会把安全置于优先。"),
    S("To shed light on gaps, publish disaggregated data.", "为阐明缺口，公布细分数据。"),
    S("Growing at the expense of equity is politically costly.", "以公平为代价的增长政治代价高。"),
    S("With regard to privacy, stricter defaults help.", "关于隐私，更严格的默认设置有帮助。"),
    S("The idea that markets always leave nothing to be desired is false.", "市场总尽如人意这一想法是错误的。"),
    S("In practice, consistent rules beat discretionary favors.", "实践中，一致规则胜过随意优待。"),
    S("It is useful to recycle these collocations in essays.", "在作文中反复使用这些搭配很有用。"),
]

DAY[30] = [
    S("Empirical verification strengthens civil accountability.", "实证核实增强公民问责。"),
    S("Influence campaigns did not acquire lasting legitimacy.", "影响运动未获得持久合法性。"),
    S("Can sustainable policies conclude growth debates fairly?", "可持续政策能否公平结束增长辩论？"),
    S("Which crucial criterion should guide final self-assessment?", "哪项关键标准应指导最终自评？"),
    S("Is progress cognitive growth or merely vocabulary volume?", "进步是认知成长还是仅词汇体量？"),
    S("Thirty days of practice compounds, doesn't it?", "三十天练习会复利，对吧？"),
    S("Retest weak sentence types before celebrating.", "庆祝前先重测薄弱句型。"),
    S("What a comprehensive archive of CET patterns this is!", "这是多么全面的四六级句型档案！"),
    S("There is still room to deepen listening next month.", "下月听力仍有深化空间。"),
    S("Insights are retained when sentences are produced aloud.", "大声产出句子时洞见得以保持。"),
    S("You have already integrated roots, phrases, and syntax.", "你已整合词根、短语与句法。"),
    S("She had verified progress against the Day 0 baseline.", "她已对照 Day0 基线核实进步。"),
    S("Next cycle will emphasize spoken shadowing daily.", "下一周期将每天强调影子跟读。"),
    S("If review continues, fluency will keep rising.", "如果复习继续，流利度将持续上升。"),
    S("If practice stopped now, attrition would accelerate.", "若现在停止练习，遗忘会加速。"),
    S("Learners who conclude with production lock in gains.", "以产出收尾的学习者锁定收益。"),
    S("Tutors recommend that sustainable habits beat cramming.", "辅导建议可持续习惯胜过临时抱佛脚。"),
    S("Because themes recycled, recognition became faster.", "因为主题循环，识别变得更快。"),
    S("Although the load was heavy, methods stayed consistent.", "尽管负荷重，方法保持一致。"),
    S("Schedule maintenance so that hard words do not fade.", "安排维持练习，以免难词消退。"),
    S("Civil discourse needs clearer evidence than slogans.", "公民话语需要比口号更清晰的证据。"),
    S("It is cumulative sentence work that builds real fluency.", "正是累积的句子训练建立真正流利。"),
    S("Never before have you practiced so many clause types.", "你从未练习过如此多种从句类型。"),
    S("Facing Day 30, treat gaps as the next syllabus.", "面对第30天，把缺口当作下一课程表。"),
    S("To keep improving, mix old roots with new articles.", "要持续进步，把旧词根与新文章混合。"),
    S("Stopping at recognition alone leaves output weak.", "仅停在识别会让产出薄弱。"),
    S("With this toolkit ready, authentic input becomes usable.", "有了这套工具，真实输入变得可用。"),
    S("The belief that thirty days finishes English is false.", "三十天学完英语这一信念是错误的。"),
    S("In the end, consistency outruns intensity spikes.", "最终，一致性胜过强度冲刺。"),
    S("It is time to convert study into daily English use.", "是时候把学习转化为日常英语使用。"),
]


def strip_old_sents(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith("#SENT ") or line.startswith("#SENTTYPE "):
            continue
        lines.append(line)
    # also drop trailing empty from previous runs
    while lines and lines[-1].strip() == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def append_bank(n: int, pairs: list[tuple[str, str]]) -> None:
    path = BANK / f"day{n:02d}.txt"
    raw = strip_old_sents(path.read_text(encoding="utf-8"))
    extra = ["#SENTTYPE " + "|".join(TYPES)]
    for i, ((en, zh), typ) in enumerate(zip(pairs, TYPES), 1):
        extra.append(f"#SENT {i}|{typ}|{en}|{zh}")
    path.write_text(raw + "\n".join(extra) + "\n", encoding="utf-8")


def sentence_section(pairs: list[tuple[str, str]]) -> str:
    lines = [
        "",
        "## 句型训练（30 种不同类型）",
        "",
        "每天练 **30 句**：遮中文跟读 → 英译中 → 中译英；注意句型标签。",
        "",
        "| # | 句型 | 英文句子 | 中文 | 学完 |",
        "|---|------|----------|------|------|",
    ]
    for i, ((en, zh), typ) in enumerate(zip(pairs, TYPES), 1):
        lines.append(f"| {i} | {typ} | {en} | {zh} | [ ] |")
    lines.append("")
    return "\n".join(lines)


def update_byday(n: int, pairs: list[tuple[str, str]]) -> None:
    path = BYDAY / f"day-{n:02d}.md"
    text = path.read_text(encoding="utf-8")
    # remove old sentence section if present
    marker = "\n## 句型训练（30 种不同类型）"
    if marker in text:
        text = text.split(marker)[0].rstrip() + "\n"
    # update header line about daily load
    text = text.replace(
        "本日 **80 词 + 40 短语**（四六级，含音标）。跟读 → 英译中 → 中译英。",
        "本日 **80 词 + 40 短语 + 30 句型例句**（四六级）。词/短语：跟读→英译中→中译英；句子：按句型标签练产出。",
    )
    path.write_text(text.rstrip() + "\n" + sentence_section(pairs), encoding="utf-8")


def update_index() -> None:
    text = INDEX.read_text(encoding="utf-8")
    text = text.replace(
        "每天 **80 个单词（均含国际音标）+ 40 个短语（均含音标）+ 词根词缀**。",
        "每天 **80 个单词（均含国际音标）+ 40 个短语（均含音标）+ 30 种不同类型句子 + 词根词缀**。",
    )
    if "30 种不同类型句子" not in text.split("学法")[0]:
        pass
    text = text.replace(
        "3. 短语整句跟读；睡前复习昨天约 20 词",
        "3. 短语整句跟读\n4. 句型表 30 句：按标签变换产出；睡前复习昨天约 20 词 + 5 句",
    )
    INDEX.write_text(text, encoding="utf-8")
    readme = README.read_text(encoding="utf-8")
    if "30 种不同类型句子" not in readme:
        readme = readme.replace(
            "| 短语（含音标） | **40** |",
            "| 短语（含音标） | **40** |\n| 不同类型句子 | **30** |",
        )
        readme = readme.replace(
            "合计约 **2400 词 + 1200 短语**。",
            "合计约 **2400 词 + 1200 短语 + 900 句型例句**。",
        )
        README.write_text(readme, encoding="utf-8")


def main() -> None:
    assert list(range(1, 31)) == sorted(DAY.keys()), sorted(DAY.keys())
    for n in range(1, 31):
        pairs = DAY[n]
        assert len(pairs) == 30, (n, len(pairs))
        assert len(TYPES) == 30
        append_bank(n, pairs)
        update_byday(n, pairs)
        print("updated day", n)
    update_index()
    print("done")


if __name__ == "__main__":
    main()
